### ISSUE TITLE
Mouse over does not restore background color

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#10]
See:  http://brunel.mybluemix.net/gallery_app/renderer?title=Brushing%2FLinking&brunel_src=data%28%27http%3A%2F%2Fbrunel.mybluemix.net%2Fsample_data%2Fwhiskey.csv%27%29+x%28Category%29+y%28Price%3Alinear%29+mean%28Price%29+bar+interaction%28select%3Amouseover%29++color%28%23selection%29+|+data%28%27http%3A%2F%2Fbrunel.mybluemix.net%2Fsample_data%2Fwhiskey.csv%27%29+x%28ABV%29+y%28Age%29+color%28%23selection%29+size%28%23selection%29&description=Whiskey+price+by+category+linked+age+and+alcohol+content+%28mouse+over+event%29&width=1000&height=400&control_height=0

(Firefox browser)
The brushing works well, but when the mouse leaves the brushed bar the original color is not restored.

**Comment by grahamwills** [comment]
The problem was that one animation would start before the other had finished. Added code to ensure that this does not happen (and also speeded up animation transitions for selection)
