### ISSUE TITLE
Label behavior varies by browser

### ISSUE THREAD

**Issue by fredesch** [Brunel-Visualization/Brunel#102]
I am using BrunelPad to look at charts. Sometimes I look at the Brunel produced (index.html) file in different browsers. Using whiskey.csv and the chart 
bar treemap x(Country, Category, Name) color(Category) size(#count) label(Name) tooltip(#all)
I see a few labels in Firefox at group level and no labels in individual rectangles. In chrome I see labels in each rectangle. 
![bartreemapchrome](https://cloud.githubusercontent.com/assets/11166887/15757879/c1a619f2-28d5-11e6-851e-7d4c88ae9f5c.png)
![bartreemapfirefox](https://cloud.githubusercontent.com/assets/11166887/15757885/c577c3b4-28d5-11e6-8a48-bee89b1789dd.png)
![bartreemapie](https://cloud.githubusercontent.com/assets/11166887/15757889/c8c39a7a-28d5-11e6-8ce4-119ca79497d1.png)

**Comment by fredesch** [comment]
Third image is IE.

**Comment by grahamwills** [comment]
Firefox has known issues with SVG and I checked and found its text height algorithm is straight up wrong; when adding the heights of enclosed items it adds extra space. I'll try a workaround for FF, but in general it appears a poor choice of browser. IE I think just is ignoring the effects. As it is no longer supported, II'd be curious how Edge works ...

**Comment by grahamwills** [comment]
I have added a fix for FF that seems to work and does not appear to impact performance. This is fixed on develop.
