### ISSUE TITLE
Square Charts

### ISSUE THREAD

**Issue by dpierucci** [Brunel-Visualization/Brunel#103]
Please add a way to specify that a chart be square, e.g. 1-1 aspect ratio.

**Comment by danrope** [comment]
Implementation Note:  Formally add the default rectangular coordinate system as the default.  Add this as a parameter to this plus transpose.

**Comment by danrope** [comment]
Feature added on /develop.  Syntax examples:

`x(summer) y(winter) rectangular(aspect:square)`
`x(summer) y(winter) rectangular(aspect:1.0)`
`x(summer) y(winter) transpose(aspect:1.0)`
