### ISSUE TITLE
effect(enter) doesn't work with transpose

### ISSUE THREAD

**Issue by lkittock** [Brunel-Visualization/Brunel#106]
When I run this syntax on the test app, the effect(enter) is ignored.  If I remove the transpose syntax it works.

data('sample:US States.csv') bar x(abbr) y(population) color(dem_rep:reds-blues) effect(enter) transpose

**Comment by grahamwills** [comment]
I may have fixed as a by-product of another change; it seems to work on the develop branch as of today. I'll investigate further

**Comment by lkittock** [comment]
Note this fix still doesn't work in Chrome.  I see it works in Firefox and Internet Explorer.

**Comment by grahamwills** [comment]
fixed on chrome on develop
