### ISSUE TITLE
Tooltip on line chart is not working correctly

### ISSUE THREAD

**Issue by dpierucci** [Brunel-Visualization/Brunel#107]
Use the try it out online page and set syntax to:
data('sample:US States.csv') line y(dem_rep) x(population) tooltip(#all)

It doesn't matter which part of the line you hover over, the tooltip is always the same.

**Comment by danrope** [comment]
The tooltip currently shows an arbitrary value.  This is a defect. 

However, a line generally has one tooltip.  Would it be possible to use both points and line to show tooltips for each value.  Note, you can use styles to make the points invisible.

**Comment by grahamwills** [comment]
Here's a way to do this, hiding the points:

line x(population) y(dem_rep) + x(population) y(dem_rep) tooltip(#all) style('opacity:0;size:20px')

**Comment by dpierucci** [comment]
Thanks Dan and Graham! I will use both a line and a point and show the point at 6px. The problem with invisible points is that it would be difficult for the user to know where to hover to get a tooltip.

**Comment by grahamwills** [comment]
On the development branch I have modified the code for tooltips to allow exactly the desired behavior without the need for invisible points. However, it can be quite hard to hover exactly over the line, so it may be advisable still to use that method

**Comment by dpierucci** [comment]
Thanks Graham!
