### ISSUE TITLE
Animation bug: effect(enter) does not work with > 1 elements

### ISSUE THREAD

**Issue by dpierucci** [Brunel-Visualization/Brunel#108]
Animation bug: effect(enter) does not work when there are more than 1 elements in the chart

Example syntax:
line x(population) y(dem_rep) + x(population) y(dem_rep) tooltip(#all) style(size:6px') effect(enter)

Here are the examples we have so far... 

1. Scatterplot with a reference line. 
2. Line and points
3. Points and points

In all of those cases, I think animating both elements would be fine, but if is is easy to make it configurable, even better.

**Comment by grahamwills** [comment]
fixed on develop. Will resolve when we promote 2.0
