### ISSUE TITLE
Graph Annotation

### ISSUE THREAD

**Issue by suntong** [Brunel-Visualization/Brunel#109]
`treemap` can use label to annotate the graph, but that doesn't work for [`heatmap`](http://brunel.mybluemix.net/gallery_app/renderer?title=Heatmap&brunel_src=data%28%27sample%3ABGG+Top+2000+Games.csv%27%29+x%28Categories%29+y%28Mechanics%29+color%28%23count%3Ared%29+style%28%27symbol%3Arect%3B+size%3A100%25%3B+stroke%3Anone%27%29+sort%28%23count%29&description=Number+of+games+for+each+category+and+game+mechanics.&width=600&height=600&control_height=0). 

Please consider adding the annotation capability to `heatmap` (and others like bar graphs) as well. 

Thanks

**Comment by danrope** [comment]
Note, labeling does work for heatmaps--if there is enough space to draw the label:  ` data("sample:US States.csv") x(Presidential_Choice) y(Region) color(#count:red) sort(#count) style('symbol:rect; size:100%; stroke:none') label(#count)`

It also works for bars:  `data("sample:US States.csv") bar x(Region) y(Rain) sort(Rain) mean(Rain) label(rain)`

**Comment by suntong** [comment]
Oh, that's the trick -- *"if there is enough space"*, i.e., make it bigger. Thx.

**Comment by danrope** [comment]
I'm going to reopen this & filing as a bug.  You **can** request a smaller font-size for the labels, but it seems it is too restrictive deciding when to not draw the label.

`data('sample:BGG Top 2000 Games.csv') x(Categories) y(Mechanics) color(#count:red) style('symbol:rect; size:100%; stroke:none') sort(#count) label(#count) style('.label {font-size:5px}') `

**Comment by grahamwills** [comment]
latest changes (for D3 4.0 compatibility) seems to have fixed this feature
