### ISSUE TITLE
Constant And Special Field example makes empty chart

### ISSUE THREAD

**Issue by fredesch** [Brunel-Visualization/Brunel#11]
Looking at http://brunel.jupyter.ninja:9080/brunel-service/docs/ Constant and Special Fields.
Clicking on the 
bar x(state) yrange(winter, 58.2) + bar x(state) yrange(summer, 58.2)
example yields a chart with both axes and no visible bars.

**Comment by danrope** [comment]
This is now working with newly updated docs:  http://brunel.mybluemix.net/docs/
