### ISSUE TITLE
Horizontal Bars' order are reversed

### ISSUE THREAD

**Issue by suntong** [Brunel-Visualization/Brunel#110]
It is a well known problem for all Horizontal Bars' to show up in reversed order, and each charting tools is having their own ways to revers the order. Please add that to Brunel's Horizontal Bars as well. 

Here is the illustration, add `transpose` to the end of [Clustered Bar Chart](http://brunel.mybluemix.net/gallery_app/renderer?title=Clustered+Bar+Chart&brunel_src=data%28%27sample%3AUS+States.csv%27%29+bar+x%28Region%2C+Presidential_Choice%29+y%28%23count%29+color%28Presidential_Choice%29&description=Counts+of+presidential+choices+of+states+within+region.&width=600&height=400&control_height=0)

what shown first, `Midwest` on LHS, is now shown last, on the bottom instead of on the top.

**Comment by grahamwills** [comment]
The commands flip and flips were added to support this feature, but they are not functional and we decided anyway that we needed to rethink this mechanism. We will add support for this explicitly in th near future. Not sure it'll make 2.0, but it'll be close

**Comment by suntong** [comment]
Thanks. looking forward eagerly to that.

**Comment by danrope** [comment]
Added "reverse" option for axes.  so, on /develop, syntax for requested chart above is:

`data('sample:US States.csv') bar x(Region, Presidential_Choice) y(#count) transpose color(Presidential_Choice) axes(x, y:reverse)`

**Comment by suntong** [comment]
Great. 

Hmm... how to turn [Clustered Bar Chart](http://brunel.mybluemix.net/gallery_app/renderer?title=Clustered+Bar+Chart&brunel_src=data%28%27sample%3AUS+States.csv%27%29+bar+x%28Region%2C+Presidential_Choice%29+y%28%23count%29+color%28Presidential_Choice%29&description=Counts+of+presidential+choices+of+states+within+region.&width=600&height=400&control_height=0) url onto /develop?

**Comment by danrope** [comment]
The new feature will be included in the Brunel 2.0 release currently expected in late August.  We will leave this git issue open until the release happens.

**Comment by suntong** [comment]
Has the Brunel 2.0 release been deployed yet? 

I got the following when trying to add `transpose reverse`:

```
Error! Could not execute Brunel: data('sample:US States.csv') bar x(Region, Presidential_Choice) y(#count) color(Presidential_Choice) transpose reverseCould not execute Brunel: data('sample:US States.csv') bar x(Region, Presidential_Choice) y(#count) color(Presidential_Choice) transpose reverse
Unknown action 'reverse(?)' while parsing action text: data('sample:US States.csv') bar x(Region, Presidential_Choice) y(#count) color(Presidential_Choice) transpose reverse
```

**Comment by suntong** [comment]
Is it working on http://brunel.mybluemix.net/ now? I saw "Try Brunel Visualization 2.0" and presume that it means Brunel 2.0 release. 

However it doesn't work for me:

These two charts are the same, 

http://brunel.mybluemix.net/brunel/interpret/d3?brunel_src=data('sample%3AUS%20States.csv')%20bar%20x(Region%2C%20Presidential_Choice)%20y(%23count)%20color(Presidential_Choice)%20transpose%20axes(x%2C%20y%3Areverse)&width=575&height=375&title=Clustered%20Bar%20Chart&description=Counts%20of%20presidential%20choices%20of%20states%20within%20region.&show_brunel=true

http://brunel.mybluemix.net/brunel/interpret/d3?brunel_src=data('sample%3AUS%20States.csv')%20bar%20x(Region%2C%20Presidential_Choice)%20y(%23count)%20color(Presidential_Choice)%20transpose%20&width=575&height=375&title=Clustered%20Bar%20Chart&description=Counts%20of%20presidential%20choices%20of%20states%20within%20region.&show_brunel=true

despite that one has the "axes(x, y:reverse)" clause. 

Please take a look. Thanks.

**Comment by danrope** [comment]
Thanks.  This appears to be a bug, so I am re-opening this issue.

**Comment by grahamwills** [comment]
Should have looked at this earlier!

This is a change we made (perhaps the only one we have made) to the Brunel syntax. Instead of specifying reverse on the axis, you specify it on the `y` command directly. We made this change as we added a lot of info to the axes, and it was making it hard to nothings like reverse the direction and NOT show an axis.

**Comment by suntong** [comment]
Thanks, so what's the new syntax of specifying reverse on the y command directly? Still `y:reverse`? Working sample code appreciated.

**Comment by danrope** [comment]
My apologies.  Should have noted this sooner.. 

`data('sample:US States.csv') bar x(Region:reverse, Presidential_Choice) y(#count) color(Presidential_Choice) transpose axes(x, y)`

**Comment by suntong** [comment]
Thanks A LOT! 
Problem solved. :+1:
