### ISSUE TITLE
Getting start in IBM Data Scientist Workbench

### ISSUE THREAD

**Issue by suntong** [Brunel-Visualization/Brunel#111]
Brunel 1.2 is now supported in [IBM Data Scientist Workbench](https://datascientistworkbench.com/). 

Please provide a bit.ly url so that on clicking it, a usable example is available in user's own notebook. I don't know how it works, but that's how I'm getting all the demo samples. Here is an example, www.bit.ly/may2016python

Thanks.

**Comment by danrope** [comment]
Hello,

Can you clarify further what you would like to see.  When I click the link above it says the resource is no longer available.

**Comment by suntong** [comment]
Ops, try this instead http://bit.ly/svmlr­, provided that you've already logged into the IBM Data Scientist Workbench. 

What's exactly I want to see is just an example (say [Clustered Bar Chart](http://brunel.mybluemix.net/gallery_app/renderer?title=Clustered+Bar+Chart&brunel_src=data%28%27sample%3AUS+States.csv%27%29+bar+x%28Region%2C+Presidential_Choice%29+y%28%23count%29+color%28Presidential_Choice%29&description=Counts+of+presidential+choices+of+states+within+region.&width=600&height=400&control_height=0)) as simple as possible to how to get Brunel work under IBM Data Scientist Workbench, because making it works is the hardest, and adopting and enhancing it will be much much easier.

**Comment by danrope** [comment]
That link still does not work for me.  I am logged in to DatascientWorkbench.

**Comment by suntong** [comment]
hmm... http://bit.ly/svmlr­

**Comment by danrope** [comment]
OK.  I got it.  
Try executing a cell like this:
```
import brunel
df = pd.read_csv("/resources/data/samples/olympic-medals/medals.csv")
%brunel data('df') x(Sport) y(#count) bar
```
This will work with a Python 2 or 3  notebook..   Essentially, Brunel is already installed and you just have to import it.  You may want to ask DatascieneWorkbench to include samples that uses Brunel or refer you to them.

**Comment by suntong** [comment]
oh, good. thanks, 

Very strange that if I type "http://bit.ly/svmlr" into the url of my browser, will work, but clicking on it from github doesn't work. So please try typing (copy/paste) "http://bit.ly/svmlr" into you browser instead. 

- How was you able to create a folder structure as complicated as "`/resources/data/samples/olympic-medals/medals.csv`" on DatascieneWorkbench? 
- Can you share out your working sample url please? from DatascieneWorkbench there is an option under the notebook to share it...
- Can you make that `medals.csv` available on the internet, say gist please? 
- Also, Can you make the  [Clustered Bar Chart](http://brunel.mybluemix.net/gallery_app/renderer?title=Clustered+Bar+Chart&brunel_src=data%28%27sample%3AUS+States.csv%27%29+bar+x%28Region%2C+Presidential_Choice%29+y%28%23count%29+color%28Presidential_Choice%29&description=Counts+of+presidential+choices+of+states+within+region.&width=600&height=400&control_height=0)) `.csv` available on the internet as well please? 

thanks

**Comment by danrope** [comment]
Here is what I did:
* Followed the link you sent
* This brought up a Jupyter notebook
* I created a new cell in this notebook &  executed the above code.
* The medals.csv data was already in there. They have a feature to the right to paste in the path of this data into the current cell.  I just clicked this & that path appeared.
* US States.csv is here:  https://github.com/Brunel-Visualization/Brunel/blob/master/gallery/src/main/webapp/sample_data/US%20States.csv

**Comment by suntong** [comment]
Oh, thanks for the explanation, I got mine works as well now. 

https://share.datascientistworkbench.com/jupyter/v1/10.114.214.106/ayTWEEkbvNSueoN/brunel-medals.ipynb

I've put into some comments, so as to make it easy for the next person. 

Thanks again for your help!!

**Comment by suntong** [comment]
Hmm...

How can I make this works? 

`%brunel data('df') x(Sport,'Event gender') y(#count) bar
`

**Comment by danrope** [comment]
Use underscores when you have spaces in field names:

`%brunel data('df') x(Sport,'Event_gender') y(#count) bar `

**Comment by suntong** [comment]
oh, Thanks. 

That didn't work, but this does:

`%brunel data('df') x(Sport,Event_gender) y(#count) bar
`
