### ISSUE TITLE
Heatmap axle order

### ISSUE THREAD

**Issue by suntong** [Brunel-Visualization/Brunel#112]
I've just tried the Heatmap with my own data, don't know if [this url](http://brunel.mybluemix.net/gallery_app/renderer?title=Heatmap&brunel_src=data%28%27sample%3ABGG+Top+2000+Games.csv%27%29+x%28Categories%29+y%28Mechanics%29+color%28%23count%3Ared%29+style%28%27symbol%3Arect%3B+size%3A100%25%3B+stroke%3Anone%27%29+sort%28%23count%29&description=Number+of+games+for+each+category+and+game+mechanics.&width=600&height=600&control_height=0) will work, but the charting code (for brunel.mybluemix.net/gallery_app) is, 

`data('6375921d-af93-41a3-8204-83fc1fc708c1') x(DOW) y(Hour) color(#count:red) sort(#count) tooltip(#count) style('symbol:rect; size:100%; stroke:none') 
`

We can see that X axle is in random order:

![image](https://cloud.githubusercontent.com/assets/422244/16421881/71d713dc-3d24-11e6-81bc-498667bcda4b.png)

Please correct it. 

Please note that ultimately, I hope it can achieve to this effect:

![image](https://cloud.githubusercontent.com/assets/422244/16422058/0b13e642-3d25-11e6-9d2a-7b1dbe39fff1.png)

I.e., 

- X axle is in correct order 
- the chart is annotated with number (Ref #109, now closed).
- to use two-color in the scale  (ref #113)
- and Y axle is reversed so that 8am comes before 9am  (above it, not below it). Ref #110. 

Thanks

**Comment by grahamwills** [comment]
Because you asked to sort by #count, that is the order that the X axis has been put in (Saturday has the highest count, sunday the lowest for your data). If you remove that the natural order will be used.

Here's some general Brunel that will help you achieve your goal. I binned some numeric data for the axes, but if your data is categorical, you won't need to do that:

`x(longitude)` y(latitude) color(population:[beige, pink, black]) label(population) tooltip(state) bin(latitude:10, longitude:10) sum(population) list(state) style('.axis path, .axis line {visibility:hidden}')`

**Comment by suntong** [comment]
thanks. 

What's the `x(longitude) y(latitude) color(population:[beige, pink, black]) label(population) tooltip(state) bin(latitude:10, longitude:10) sum(population) list(state) style('.axis path, .axis line {visibility:hidden}')` code for? Which url is it meant for? 

I tried the above url, but got an error?

**Comment by grahamwills** [comment]
It uses a standard sample data set which i forgot to include. Here's the full Brunel command:

data('sample:US States.csv') x(longitude) y(latitude) color(population:[beige, pink, black]) label(population) tooltip(state) bin(latitude:10, longitude:10) sum(population) list(state) style('.axis path, .axis line {visibility:hidden}')

that will work on[ https://brunelvis.org/try]( https://brunelvis.org/try)   for example

**Comment by suntong** [comment]
Thanks. 

So, it is more a three-color theme, instead of a bi-color gradient changing way.

![image](https://cloud.githubusercontent.com/assets/422244/16496483/1bf320da-3ec0-11e6-8be3-09b1adde2512.png)

Hmm..., that has its usage, but for heatmap specifically, I think the bi-color gradient changing way looks much more natural. Please refer to my above searborn graph for reference.

**Comment by grahamwills** [comment]
absolutely, design it as you like. Check out the docs if you have any questions
