### ISSUE TITLE
bi-color scale

### ISSUE THREAD

**Issue by suntong** [Brunel-Visualization/Brunel#113]
please make it possible to use two-color in the scale (ref #112 ). Thx.

**Comment by danrope** [comment]
Try: ` data('6375921d-af93-41a3-8204-83fc1fc708c1') x(DOW) y(Hour) color(#count:[white,purple]) sort(#count) tooltip(#count) style('symbol:rect; size:100%; stroke:none') `

Is this what you are looking for?  If so, full docs are in the "Aesthetics" section in the [online docs](http://brunel.mybluemix.net/docs/).

**Comment by grahamwills** [comment]
I added an example to #112

**Comment by suntong** [comment]
I'm afraid that I cannot make Brunel's Heatmap scale to bi-color. I'm tried many combinations, but just can't make it look anywhere close to bi-color scale. 

The data I want to chart is [here](https://gist.github.com/suntong/e7c6afe457e5d4746ca8dc3a59067d7f), which is aggregated from [this](https://gist.github.com/suntong/416bcaa0ae3156c5a15cbcc7018344d1). 

This is the standard Seaborn Heatmap 

![image](https://cloud.githubusercontent.com/assets/422244/17071340/f51f91e8-502e-11e6-8593-86524c1fa05c.png)

From this Seaborn Heatmap we can clearly see where the "focuses" are. I can't make Brunel's Heatmap looks anywhere close to it. 

Can somebody show how to create a bi-color scale Brunel's Heatmap which look like this please?

Thanks

**Comment by danrope** [comment]
Here is an example that is fairly close assuming the aggregations are averages.  Note, you will need to use the pre-aggregated data-- or restructure the aggregated data:

`data('https://gist.githubusercontent.com/suntong/416bcaa0ae3156c5a15cbcc7018344d1/raw/6fd49a1be8ce7278bd7fcd411c3300c42cbbd0f5/HeatMap.csv') x(DOW) y(Hour) color(changes:[white, purple]) label(changes) tooltip(#all) mean(changes) style('symbol:rect; size:100%;) stroke:none')`

- Flipping the y-axis is addressed here:  https://github.com/Brunel-Visualization/Brunel/issues/110
- The labels not appearing is addressed here:  https://github.com/Brunel-Visualization/Brunel/issues/109
- Scales starting below zero is mentioned here:  https://github.com/Brunel-Visualization/Brunel/issues/104

**Comment by suntong** [comment]
Thanks dan, 

This is how it looks (for `data('https://gist.githubusercontent.com/suntong/416bcaa0ae3156c5a15cbcc7018344d1/raw/6fd49a1be8ce7278bd7fcd411c3300c42cbbd0f5/HeatMap.csv') x(DOW) y(Hour) color(changes:[white, purple]) label(changes) tooltip(#all) mean(changes) style('symbol:rect; size:100%;) stroke:none')`), 

![image](https://cloud.githubusercontent.com/assets/422244/17107039/95e6d126-525b-11e6-947f-9d8fd8043bb5.png)

The problem is, I'd called it single-color theme, as it looks like _there are holes in the graph_ without data, but in fact, the bi-color theme can clearly shown all data are available:

![image](https://cloud.githubusercontent.com/assets/422244/17071340/f51f91e8-502e-11e6-8593-86524c1fa05c.png)

Further specifying two color does not means we will get bi-color scale, because `white` is actually _no-color_ on the normal web display. As soon as Ichange the "`white, purple`" to "`beige, purple`", it shows that two-color specification actually give three-colors:

![image](https://cloud.githubusercontent.com/assets/422244/17107354/cf231ba6-525c-11e6-9919-fa4b803d878f.png)

Ref: [here, two-color specification actually give three-colors](http://brunel.mybluemix.net/brunel/interpret/d3?brunel_src=data(%27https%3A%2F%2Fgist.githubusercontent.com%2Fsuntong%2F416bcaa0ae3156c5a15cbcc7018344d1%2Fraw%2F6fd49a1be8ce7278bd7fcd411c3300c42cbbd0f5%2FHeatMap.csv%27)%20x(DOW)%20y(Hour)%20color(changes%3A%5Bbeige%2C%20purple%5D)%20label(changes)%20tooltip(%23all)%20mean(changes)%20style(%27symbol%3Arect%3B%20size%3A100%25%3B)%20stroke%3Anone%27)&width=775&height=425&title=&description=&show_brunel=true)

So, please consider again to make the two-color specification means gradient fill from one color to another, just like the above Seaborn Heatmap, instead of giving three-colors. 

Thanks

**Comment by danrope** [comment]
I am re-opening this.  We will add a way to force it to just 2 colors.

**Comment by suntong** [comment]
Thanks Dan.

**Comment by grahamwills** [comment]
In the 2.0 release (code now on master, release strongly expected in the next couple of days) we will add the option to specify the middle color as 'none', so the following will make a "true" 2 color scale:  

`color(field:[blue,none,red])`

The reason for the default to three colors is that themes common use for a 2 color scale is for a divergent field, one where you want to emphasize the ends. For this, a neutral middle value is much better for interpretability. A color scale going from one hue to another is tricky for people to interpret unless the colors are chosen carefully, so we don't default to that and require an extra step of specifying `none` to make a true 2-color scale.

As a note, we are using HCL interpolation rather than RGB, which ensures that colors do not get mixed into "muddy" grayish values. If you need a more RGB-ish look, manually calculate the internal RBG values you want and make a 5-color scale and it should look pretty close.

**Comment by suntong** [comment]
:+1:
