### ISSUE TITLE
Ability to control the label chart elements

### ISSUE THREAD

**Issue by lkittock** [Brunel-Visualization/Brunel#115]
I would like the ability to control the positioning of the labels on a chart.  Ideally I would like to see a preferred and backup option.  For example, with this chart:

 bar x(gender) y(#count) label(#count) transpose

I would like the count label to be right-aligned, inside the chart.  However if the bar is too short to fit the label inside the bar, I would like to set it to be left-aligned, at the top of the chart.

**Comment by lkittock** [comment]
Another option we would like is to allow text to spill outside of the bar, so if the bar is too short, and we are left-aligned, the text will just continue on outside of the bar.

**Comment by grahamwills** [comment]
Initial work might be an option so that if a label doesn't fit inside, it is moved outside

**Comment by grahamwills** [comment]
Added significant styling options on develop -- I did not add a "back-up" facility, but instead modified the label positioning code so that labels that were partially outside are moved inside the chart area. I think this works well for the cases given, as well as helping other situations.
