### ISSUE TITLE
Change bar attributes on hover

### ISSUE THREAD

**Issue by lkittock** [Brunel-Visualization/Brunel#116]
For a simple bar chart like this one:

bar x(gender) y(#count) label(#count) transpose

I would like to have the bar only show as a thin bar with the label above the bar, like this:

![image](https://cloud.githubusercontent.com/assets/19230800/16495493/59ee0970-3eb3-11e6-8047-aed810bf14fe.png)

However, when we hover over the bar, I would like to be able to change the thickness of the bar, so it moves up, covering the label (and allowing the label text to change color at the same time).

![image](https://cloud.githubusercontent.com/assets/19230800/16495566/9be703ae-3eb3-11e6-9b55-ad7e350dd769.png)

**Comment by grahamwills** [comment]
Added the CSS class "selected" to both bars and labels, so they can both be dynamically styled
