### ISSUE TITLE
Callback on events like hover, click

### ISSUE THREAD

**Issue by lkittock** [Brunel-Visualization/Brunel#117]
When clicking on or hovering over an element on a chart, I would like an way for Brunel to pass this information on to my JavaScript code, so I can act on this event.  Ideally you would provide one or more pieces of information about what is being clicked/hovered, for example, the X and legend data values (or at a minimum the row number in the data).

**Comment by grahamwills** [comment]
(not for legend initially)

**Comment by grahamwills** [comment]
added `interaction(call: ....)` to allow this and documented it in [api.html](https://github.com/Brunel-Visualization/Brunel/blob/develop/gallery/src/main/webapp/docs/api.html)
