### ISSUE TITLE
Ability to control the spacing on bars

### ISSUE THREAD

**Issue by lkittock** [Brunel-Visualization/Brunel#118]
When I create a bar chart, I would like to control the spacing of the bars.  I want to set the width of the bar to a specific value, and the spacing between the bars to a specific value.  If there is left over space, (because of too few bars), just leave it empty.  See image below for an example.

![image](https://cloud.githubusercontent.com/assets/19230800/16495923/0c60a56c-3eb5-11e6-8a8a-f33806a4902d.png)

**Comment by danrope** [comment]
This feature needs to be evaluated further for feasibility

**Comment by grahamwills** [comment]
maybe use pan and zoom to get to this view

**Comment by grahamwills** [comment]
With the new (on develop) ability to programmatically set the zoom levels, this feature is possible by creating a standard (transposed) bar chart and then zooming to ensure each category has exactly 20 pixels (or whatever is desired). Note that you will have to a activate pan zoom for the categorical axis by adding `interaction(panzoom:x)` 

This can be achieved by adding JavaScript code immediately after the chart has been built to set the zoom level. Here is some sample code to do this:

    var chart = v.charts[0], scx = chart.scales.x, range = scx.range(), nCats = scx.domain().length;
    var width = Math.abs(range[range.length-1] - range[0]); 
    var desiredGap = 20;
    var desiredRange = desiredGap * nCats;
    chart.zoom( {s: desiredRange/width}, 0 );
