### ISSUE TITLE
Ability to pan and zoom with categorical axis

### ISSUE THREAD

**Issue by lkittock** [Brunel-Visualization/Brunel#119]
When I have a chart with a categorical axis (like a bar chart), I would like to be able to use the pan and zoom feature so I can limit the number of bars shown.  This should only happen in the categorical dimension, so the Y-axis range remains the same but I'm able to zoom down to just a few bars, then scroll back and forth showing different subsets of bars.

**Comment by danrope** [comment]
Note:  additional request to supply an initial pan/zoom value will also provide a work-around to https://github.com/Brunel-Visualization/Brunel/issues/118
