### ISSUE TITLE
size as % not working in documentation example 

### ISSUE THREAD

**Issue by fredesch** [Brunel-Visualization/Brunel#12]
In going through http://brunel.jupyter.ninja:9080/brunel-service/docs/ Aesthetics
clicked on the various examples.  When size is expressed as a percentage, no change in the chart is seen.  

I tried the 
color(winter) x(winter) y(summer) style("size:200%") 
example and did not see a change, then switched 200% to 600% and 1000% and saw no change.

**Comment by danrope** [comment]
The documentation on ninja was out of date.  New docs have been posted here:  http://brunel.mybluemix.net/docs/.  Updated links in wiki pages to point to new docs.
