### ISSUE TITLE
Brunel Online Builder App / Interactive Tut not working?

### ISSUE THREAD

**Issue by softpunch** [Brunel-Visualization/Brunel#123]
Hi!

I'm on a Mac running OS 10.11, using up-to-date versions of Chrome and Firefox.
I don't have any JavaScript-blockers on.

When I visit the "Try Brunel Visualization" page, the visualizer canvas throws an error:
"Error! Could not execute Brunel: data('sample:US States.csv') bubble label(abbr) size(population) color(dem_rep:reds-blues)Could not execute Brunel: data('sample:US States.csv') bubble label(abbr) size(population) color(dem_rep:reds-blues)
null"

I tried switching to different viz models, and all of them threw errors.

The online tutorial throws an error as well, "Error! nullnull."

![screen shot 2016-07-09 at 10 49 56 pm](https://cloud.githubusercontent.com/assets/19437970/16711409/ce074292-4627-11e6-9668-e96a05e71e7c.png)
![screen shot 2016-07-09 at 10 50 10 pm](https://cloud.githubusercontent.com/assets/19437970/16711410/d20f9a6a-4627-11e6-8e0d-efb9ff729dc5.png)

**Comment by danrope** [comment]
Thank you for letting us know.  The service should now be operational once again.
