### ISSUE TITLE
Tooltip shows too many decimal places

### ISSUE THREAD

**Issue by lkittock** [Brunel-Visualization/Brunel#129]
Using the data from the attached Drug1n.xlsx file, create a simple chart with Na as the tooltip, such as this:

bar x(K) y(Na) tooltip(Na)

Hover over a bar.  It shows the full 6 decimal digit precision.  This seems a bit much.  If I expand Na to have more decimals, it shows all decimals.  It would be nice to show only a couple of decimal places, assuming they are not all showing ".00".

[DRUG1n.xlsx](https://github.com/Brunel-Visualization/Brunel/files/388746/DRUG1n.xlsx)

**Comment by grahamwills** [comment]
made several improvements to labeling, but for the purposes of this issue, it now uses a better default. Previously it tried for 8 significant places. Now it will look for a number that allows variations in value of 0.01% to be seen (so 4 places for data in the range 0-1) 

seems to work pretty well overall.
