### ISSUE TITLE
rectangular(aspect:1) does not make the chart square

### ISSUE THREAD

**Issue by lkittock** [Brunel-Visualization/Brunel#130]
When I use rectangular(aspect:1), the X and Y aspect ratio is indeed set to 1, but if I have a chart that is wider than it is tall, an empty portion of the graph is extended into the right of the chart, so the chart itself remains rectangular, even though the data lies in a square portion of the chart.

I would like to have an option to force not only the aspect ratio to be 1, but to force the graph itself to be square.

**Comment by grahamwills** [comment]
We will add an additional parameter to coordinates `rectangular` and `transpose` that will allow the inner space between axes to be defined as square
