### ISSUE TITLE
dropline doesn't turn off by clicking background area

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#136]
Here is the syntax we are using:

point x(Predicted) y(Observed) size(Frequency:[100%, 800%])  tooltip("Predicted: ", Predicted, "<br>Observed:", Observed, "<br>Frequency:", Frequency) rectangular(aspect:1, square) interaction(call) style('.element.point {size:4px; fill: #41D6C3; stroke-width: 0px; fill-opacity: 0.25}  .element.point:hover {stroke: #41D6C3; stroke-width: 1px} ')  + guide(y:x) style('stroke: #dfdfdf') + point x(Predicted) y(Observed) interaction(call) style('fill: #41D6C3; stroke-width: 0px; fill-opacity: 1.0') tooltip("Predicted: ", Predicted, "<br>Observed:", Observed, "<br>Frequency:", Frequency) title("Size = frequency":footer) effect(enter) axes(x:grid, y:grid) style('.inner {stroke:#e0e0e0; stroke-width:1px} .footer {fill: #e0e0e0;font-size:12px;label-location:right; padding-right:225px;} .axis {label-location:left} .grid{opacity:1} .grid.x {stroke:#777677; stroke-dasharray:2,2} .grid.y {stroke:#777677; stroke-dasharray:2,2} .axis.x .title {label-location:left; font-size:14px;  padding-bottom:5px} .axis.x .tick text{fill:#e0e0e0; font-size:12px; padding-bottom:15px; padding-top: 5px} .axis .tick line{size:8px; stroke-width:1px} .axis.y .tick text{ fill:#e0e0e0; font-size:12px; padding-right: 5px; padding-left: 15px}  .axis.y .title {label-location:left; padding-left:5px; font-size:14px} ')

**Comment by grahamwills** [comment]
I replaced the fields with ones from our standard data set, and tried it out with the latest code on 
https://brunelvis.org/try. It seems to work there, with the issue that multiple elements are not working well. I will fix that issue, but the core defect mentioned here I cannot reproduce.

Is it possible you are using an older version? 



------------------------
data('sample:US States.csv') point x(summer) y(winter) rectangular(aspect:1, square) size(Population:[100%, 800%]) tooltip('Predicted: ', summer, 'Observed:', winter, 'Frequency:', Population) style('.element.point {size:4px; fill: #41D6C3; stroke-width: 0px; fill-opacity: 0.25} .element.point:hover {stroke: #41D6C3; stroke-width: 1px} ') interaction(call) + guide(y:x) style('stroke: #dfdfdf') + point x(summer) y(winter) tooltip('Predicted: ', summer, 'Observed:', winter, 'Frequency:', Population) axes(x:grid, y:grid) style('fill: #41D6C3; stroke-width: 0px; fill-opacity: 1.0') style('.inner {stroke:#e0e0e0; stroke-width:1px} .footer {fill: #e0e0e0;font-size:12px;label-location:right; padding-right:225px;} .axis {label-location:left} .grid{opacity:1} .grid.x {stroke:#777677; stroke-dasharray:2,2} .grid.y {stroke:#777677; stroke-dasharray:2,2} .axis.x .title {label-location:left; font-size:14px; padding-bottom:5px} .axis.x .tick text{fill:#e0e0e0; font-size:12px; padding-bottom:15px; padding-top: 5px} .axis .tick line{size:8px; stroke-width:1px} .axis.y .tick text{ fill:#e0e0e0; font-size:12px; padding-right: 5px; padding-left: 15px} .axis.y .title {label-location:left; padding-left:5px; font-size:14px} ') effect(enter) interaction(call) title('Size = frequency':footer)

**Comment by grahamwills** [comment]
I fixed a related defect, so I believe that for single elements, this should now work
