### ISSUE TITLE
SSL protected notebooks fail to render because of mixed content

### ISSUE THREAD

**Issue by joshisa** [Brunel-Visualization/Brunel#140]
**Bug Type**:  Regression (See discussion in #75) from Brunel 1.2
**Environment**:  IBM Bluemix Scala Notebook
**Commands Invoked**:

```
%AddJar -magic https://brunelvis.org/jar/spark-kernel-brunel-all-2.0.jar
```

```
%%brunel
data('sample:whiskey.csv') line x(Rating) y(Price) smooth(Price) + data('sample:whiskey.csv') point x(Rating) y(Price)
```

**End User Symptom**:  
Brunel magic cells fail to display any content.  Rather, a blank cell output is rendered.

**Observed Errors**:  
Mixed Content warning within browser console for loading of **brunel.1.1.css** and **sumoselect.css**:
![brunel2 0_mixedfail](https://cloud.githubusercontent.com/assets/1133849/18093453/df15026a-6e9d-11e6-99d9-4d51e0dbfcf9.png)

**Workaround**: Invoke a Chrome browser with the "--allow-running-insecure-content" flag

**Comment by danrope** [comment]
I tried it out and it seems the bluemix service is using an older version of brunel despite the `%AddJar` command.   This can be seen in the reference to "brunel.1.1.css".  Will continue to investigate..

**Comment by fellerj** [comment]
Dan, any progress in finding out why Bluemix continues to use the older 1.1 version of brunel.   Could Bluemix change to at least pre-load brunel 2.0 instead of 1.1?

**Comment by danrope** [comment]
I tried again today and found the same problem.  I also see it on Data Science Experience.  Since we do not have any control over this issue I am closing it.  If not already, please submit this issue with the IBM Data Science Experience team.
