### ISSUE TITLE
Separate zooming from zooming and panning

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#142]
when zooming, we want to see the zooming in on the center of the visualization, just like when your click + from google map.

**Comment by grahamwills** [comment]
When you use chart.zoom() to get the current transform, it will give you the current offset and scale
With knowledge of the chart size, you can then create a new scale and offset to zoom around the center of the chart.

The logic roughly goes like this:
 - First translate the center of the current chart to 0,0
 - Change scale
 - translate back to 0,0

It's a common geometric problem, you should be able to find an online algorithm that allows you to do so

**Comment by cjiang-ibm** [comment]
Hi Graham,

For some reason, the offsets returned from chart.zoom() are always zero 
but I did see the center of the chart moved in both x and y direction.

Here is the piece of codes I'm using:


var chart = brunelJS.charts[0];
var origZoom = chart.zoom();

//check current scale value.
origZoom .toString(); ====> translate(0,0) scale(1) 


//apply scale value 1.2:
origZoom.zoom( origZoom.scale(1.2) );
origZoom .toString(); ====> translate(0,0) scale(1.2) 



What is the right function to get the offset values?

Thanks
Jane

**Comment by grahamwills** [comment]
You will need to add translation values to ensure you zoom around the 
center of the chart. Otherwise you will zoom around the origin




Graham Wills
STSM, Analytics and Data Science
IBM Watson Analytics
work:
gwills@us.ibm.com
personal:
graham@willsfamily.org
blog:
workingvis.com
