### ISSUE TITLE
(Enhancement) Drilling up/down in a tree map 

### ISSUE THREAD

**Issue by ap-aep** [Brunel-Visualization/Brunel#144]
While expanding/collapsing is natural for the trees, a tree map needs instead to support drilling up/down the hierarchy: 
- when user selects an expanded section it should become the only expanded section with its expanded contents visualized in the tree map (as if the user drills in into this branch of the tree);
  the rest of the branches appropriate for visualization need to be in the collapsed state; 
- if a section has already  been drilled into, the expanding/collapsing action on the same section may work as returning to visualizing the tree map with expanded sections one level up;
- expanding/collapsing actions on the sections that do not support expanding/collapsing may be handled in 2 different ways: the actions may be ignored, or they can be sent to the encapsulating section;
- An expanding action for any collapsed section on the tree map would lead to drilling in into the selected collapsed section.

To optimize the use of the canvas, it might make sense to visualize only the collapsed _parent_ sections of the currently selected section as opposed to all collapsed sections.

**Comment by grahamwills** [comment]
Since both use the same hierarchical structure, this is essentially the same as  issue #180

**Comment by grahamwills** [comment]
For tree maps, you can specify `interaction(expand)` to enable this interaction. When active, double-clicking on a node will make it the root of the treemap, hiding everything except its descendants and filling the space with that node. To undo the process shift-double-click anywhere in the tree. Note that the sate is kept so if you expand out three times in a row, you will need to undo three times to get back to the original state.
