### ISSUE TITLE
Brunel visualization is not captured as a snapshot in Jupyter notebooks

### ISSUE THREAD

**Issue by ap-aep** [Brunel-Visualization/Brunel#146]
When a visualization  is done using R or Python in Jupyter notebooks, downloading a notebook and importing it as a new notebook preserves the visualizations. However, Brunel visualizations are lost. A user needs to rerun the visualization code every time the user reopens the notebook.

**Comment by danrope** [comment]
I was unable to replicate this.  I did the following when running Jupyter locally:

* Open Notebook
* Click File/Download As../ IPython Notebook
* Open the downloaded notebook in Jupyter

I see the visualizations.

**Comment by danrope** [comment]
Closing as this does not seem to be a Brunel issue.
