### ISSUE TITLE
Unbalanced tree visualization issues

### ISSUE THREAD

**Issue by ap-aep** [Brunel-Visualization/Brunel#147]
Brunel aligns the leaf nodes of a tree to display them on the same level.  In the same time, the leaf node may not be located on the deepest level of the tree. In this case, Brunel places the leaf node at the deepest level and introduces non-existing parent nodes: 1 parent node per the level on which this branch does not have nodes. With collapse/expand functionality, this requires user to expand fake collapsed nodes multiple times.

**Comment by grahamwills** [comment]
With the current implementation, fields specified as positions define the intermediate nodes (the inner nodes) of the tree. This leads to a complete tree where the leaf nodes all have the exact same depth -- if there are N position fields, the leaf node will have N ancestors, each one being the value of the field for that level. Can you attach an example data file and Brunel command for the issue so i can explore it more clearly?

**Comment by grahamwills** [comment]
empty inner cells are now ignored
