### ISSUE TITLE
Usability issues for collapsing/expanding in trees

### ISSUE THREAD

**Issue by ap-aep** [Brunel-Visualization/Brunel#148]
When the size of the node is specified, the tree is visualized with the nodes as very small dots which are difficult to point at to expand/collapse (double-click).

**Comment by grahamwills** [comment]
trees do not change the sizes of nodes when expanding/collapsing -- only space-filling hierarchy visualizations (treemap and bubble) now do

**Comment by ap-aep** [comment]
Perhaps, this may be a future enhancement to allow users to match the size of the nodes and the thickness of links to the attributes of the data set in a tree.
