### ISSUE TITLE
(Enhancement) A tool tip for non-leaf nodes in trees and tree maps

### ISSUE THREAD

**Issue by ap-aep** [Brunel-Visualization/Brunel#151]
A tool tip is currently supported for trees and tree maps in leaf nodes. However it might be of interest to collect aggregated measures and other information on the tree and show them as the tool tip for non-leaf nodes. Effectively, this would require defining different tool tips for different types of nodes.

**Comment by grahamwills** [comment]
Added support for this on develop branch, will be present in master Jan 6
