### ISSUE TITLE
Clicking on the collapsed node may lead to tree reloading

### ISSUE THREAD

**Issue by ap-aep** [Brunel-Visualization/Brunel#152]
When the tree is loaded with the automating pruning option, clicking on the collapsed node at the lowest available level leads to reloading the tree instead of expanding the collapsed node. When the tree is reloaded only the root node and its collapsed child nodes are visualized.

**Comment by grahamwills** [comment]
Added code so auto-pruning only happens the first time the tree is created, not when interacted with
