### ISSUE TITLE
%%brunel cell magic doesn't seem to work with Jupyter password authentication enabled

### ISSUE THREAD

**Issue by torsstei** [Brunel-Visualization/Brunel#153]
Since I enabled Jupyter for password authentication via HTTP I don't get any graphics displayed anymore. Instead there is a stack trace in the logs:

  :
File "/opt/conda/lib/python3.5/site-packages/jupyter_client/session.py", line 859, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: b'd32065cf72c2f9415b9ab43421a11fe90d81a98610fa0dbb5d5548ac330901ab'

**Comment by danrope** [comment]
Hi.  Can you check whether other cell magics work?

```
%%HTML
Hello
```

**Comment by torsstei** [comment]
Hi Dan, yes, the other cell magics work fine.

**Comment by torsstei** [comment]
Not reproducible anymore. Closing the issue.
