### ISSUE TITLE
Labels are duplicated on a pie chart

### ISSUE THREAD

**Issue by mpierre0220** [Brunel-Visualization/Brunel#157]
I have a pie chart that is displaying months as labels. Each month is repeated twice. The brunel below reproduces the problem:

data('https://dwotrends.mybluemix.net/projectcommits?projectid=39892981') stack polar bar y(commits) color(month) label(month,commits) legends(auto) title('developerWorks Open: Commits for hyperleger-archives/fabirc  over the last six months') style('{font-family:Helvetica;}') tooltip(#all)

**Comment by grahamwills** [comment]
Cannot replicate this; can you attach a picture? And maybe the generated HTML if that is possible

**Comment by mpierre0220** [comment]
![pie](https://cloud.githubusercontent.com/assets/6641778/18492649/649d2bfa-79da-11e6-9213-a01bbc0c864f.jpg)

Picture is above

here is the jade template that is rendered 
doctype html	
html
  head    
    link(rel='stylesheet' type='text/css' href='//brunelvis.org/js/brunel.2.0.css' charset='utf-8')
    link(rel='stylesheet' type='text/css' href='//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css' charset='utf-8')
    link(rel='stylesheet' type='text/css' href='//brunelvis.org/js/sumoselect.css' charset='utf-8')

    //    D3 Copyright ï¿½ 2012, Michael Bostock
    //    jq1102 Copyright ï¿½ 2010 by The jq1102 Project
    //    sumoselect Copyright ï¿½ 2014 Hemant Negi
    //
    script(src='//cdnjs.cloudflare.com/ajax/libs/d3/4.2.1/d3.min.js' charset='utf-8')
    script(src='//d3js.org/topojson.v1.min.js')
    script(src='//code.jquery.com/jquery-1.10.2.js' charset='utf-8')
    script(src='//code.jquery.com/ui/1.11.4/jquery-ui.js' charset='utf-8')
    script(src='//brunelvis.org/js/brunel.2.0.min.js' charset='utf-8')
    script(src='//brunelvis.org/js/brunel.controls.2.0.min.js' charset='utf-8')    
  body
      include menu.jade
      
      svg(id="visualization" width="800" height="768")
            
      div.brunel(id="controls")
         h2 Commits Chart
  script.
      var project="#{project}";
      var data="#{data}";
      var fields="#{fields}";
      var project="#{project}";
      var chart="#{chart}";
      data=data.replace(/;/g,'\n');
      data=data.replace(/[ ]/g,'-');
      //alert(data);
      data=fields+'\n'+data;
      //alert(data);
      var styleElement;               // Element to put our custom Brunel styles into
      //Dynamically sets the CSS for use by the Brunel visualization
      function setCSS(css) {
          if (!styleElement) {
              styleElement = document.createElement("style");
              document.getElementsByTagName("head")[0].appendChild(styleElement);
          }
          styleElement.innerHTML = css;
      }
      //Dynamically load JS given the brunel and the data as CSV
      function loadBrunelJS(brunel_src, width, height, visid, csv) {
          var queryParam = {
              src: brunel_src,	//Brunel script
              width: width,		//Output width
              height: height,		//Output height
              visid: visid		//id for <svg> tag
          };
          var url = "https://brunel.mybluemix.net/brunel/interpret/d3?" + $.param(queryParam);
          $.ajax({
              type: "POST",
              headers: {
                  'Accept': 'application/json',
                  'Content-Type': 'text/plain'
              },
              data: csv,	          //The data as CSV
              url: url,
              success: function (result) {
                execBrunel(result);
              },
              error: function (xhr, textStatus, errorThrown) {
                  console.log(xhr.responseText);
              }
          });
      }
      //Execute the returned Javascript and set the CSS that Brunel requires
      function execBrunel(brunelJSON) {
          setCSS(brunelJSON.css);
          eval(brunelJSON.js);
      }
      var charts=["com", "pcom", "ncm", "cobm", "chord"];
      var found=10;
      for (c in charts) {
         if (chart == charts[c]){
            found=c;
            break;
         }
      }
      
      //alert("before calling dwotrends");
      //var brunel = "bar x(month) y(commits) sort(commits) title('developerWorks Open: Commits for "+project+" over the last six months') style('{font-family:Helvetica;}') tooltip(#all)  style('fill:red')";
      //var brunel = "bubfoundble color(month) size(commits) label(month,commits) legends(all) title('developerWorks Open: Commits for "+project+" over the last six months') style('{font-family:Helvetica;}') tooltip(#all)";
      //var brunel = "bubble color(month) size(commits) label(month,commits) legends(all) title('developerWorks Open: Commits for "+project+" over the last six months') style('{font-family:Helvetica;}') tooltip(#all)";
      var brunels = [
      "line x(month) y(commits) axes(x,y:grid) tooltip(#all) + point x(month) y(commits) axes(x:grid,y:grid) tooltip(#all) title('Commits Over Months for project "+project+"')",      
      "bar y(commits) tooltip(#all) stack polar percent(commits) color(month) label(month, commits) legends(auto) title('Proportion of Commits Over Months for project "+project+"')",  
      "bubble x(month) color(month) size(commits) label(month) sum(commits) legends(none) title('Number of commits per months for "+project+"')",
      "bar x(month) y(commits) axes(x,y:grid) tooltip(#all) sort(commits) transpose title('Number of Commits Ordered by Month for preoject "+project+"')",
      "chord x(month) y(commits) color(commits) tooltip(#all) title('Commits for "+project+" over the last six months')"
      ];
      var brunel=brunels[found];
      
      //Show the chart
      //var response=mos+counts
      loadBrunelJS(brunel, 600, 600, "visualization", data);

**Comment by grahamwills** [comment]
Got it now. The data you are using has the pie "category" as a date, which is treated as a numeric variable when we are showing it as a color, so the scale is a continuous one. For this case, you really want it to be categorical so we get a single color for each distinct time point, rather than interpolating the dates!

We do have an outstanding feature to allow you to override the default Brunel allocation to numeric or categorical, but that is not in there yet (if you are using a notebook, it WILL work, as you can use the notebook data frame to set the type, and Brunel respects that). So I think you'll need a work around, the simplest way of which is to make the field not readable as a date -- maybe reformat it that way.
