### ISSUE TITLE
reference line (guide(y:t)) doesn't work with zoom/pan

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#158]
1. syntax to see the problem:
 point x(x:[0,1]) y(y:[0,1]) +  guide(y:t)

2. drag the chart along y-axis up about 0.3 and then drag the chart along x-axis about 0.4.

3. you will see, reference line is NOT y=x anymore.

**Comment by grahamwills** [comment]
y:t says that y is a function of 't' --this is the parametric version -- it runs form 0 to 1 always.
If you want y to be a function of x, you should use `guide(y:x)` instead

**Comment by cjiang-ibm** [comment]
guide(y:x) fixed the problem. Thanks
