### ISSUE TITLE
Support weight variable

### ISSUE THREAD

**Issue by lkittock** [Brunel-Visualization/Brunel#159]
I have data that is pre-binned, like this:
value     frequency
25          10000
32           8000
12           2000

I'm drawing a histogram with it, and right now the only way I can see to do this is to replicate each value by the frequency count, so I have 10,000 values at 25, 8,000 values at 23, etc.

Can you add a replication weight, something like: weight(wvar) to the syntax?

**Comment by grahamwills** [comment]
If you have pre-binned data x with weights wvar, you should just be able to use simple bar chart syntax to make that work. So long as your data has a regular spacing, brunel will detect that and should give bars with that degree of spacing.

Here's an example syntax for your case:

`bar data('raw:c,wvar;25,10000;32,8000;12,2000') x(c) y(wvar)`

If you have many rows and you want Brunel to do MORE aggregation, it's a little harder. It will probably only work well with data you want to sum, in which case you add the terms `bin(c:10) sum(wvar)` to do more summing on the results. You'll need to explicitly request a rough number of bins to use for the binning, as Brunel does not know that the things you are summing are counts, and so will not guess a good number for the bin sizes (it'll probably be way too few)
