### ISSUE TITLE
Builder: Editing data should clear title and description

### ISSUE THREAD

**Issue by grahamwills** [Brunel-Visualization/Brunel#16]
When the brunel is edited, the title and description are rarely right -- should kill them

**Comment by danrope** [comment]
I didn't fix this..  We should just confirm we still want to do this with the new design given that the title and description can now be edited by the user.  For minor Brunel changes it might be bad to blast away their title/description..

**Comment by grahamwills** [comment]
Good point. I'm going to close this. If we feel we ned to do something more, we can add something clearer later.
