### ISSUE TITLE
The animate feature does not work with Spark Kernel

### ISSUE THREAD

**Issue by sourav-mazumder** [Brunel-Visualization/Brunel#160]
Hi,

Whenever I tried animate feature from Spark Kernel I got this error - Unknown action 'animate(?)' while parsing action.

Wondering whether this feature is at all supported yet.

Regards,
Sourav

**Comment by danrope** [comment]
Strongly suspect this is a duplicate of git issue #140.  The cause for that issue is that `%AddJar` is not allowing use of a later version of Brunel in the Bluemix hosted service.

**Comment by danrope** [comment]
This is a duplicate of issue #140.  I am closing this one as well since we have no control over it.
