### ISSUE TITLE
Tool tips for hierarchical data filled with NA in R display '?'

### ISSUE THREAD

**Issue by ap-aep** [Brunel-Visualization/Brunel#164]
Tool tips for hierarchical data filled with NA in R display '?': they should show empty values as the output instead.

**Comment by danrope** [comment]
This appears to be fixed in 2.2 (currently on /develop branch).  Also note that separate data() statements can now be provided for tree where one describes the nodes and the other describes the connections.  This technique allows for individual tooltips on the non-leaf nodes.
