### ISSUE TITLE
Error bars for standard deviation (or standard error)

### ISSUE THREAD

**Issue by r2o2** [Brunel-Visualization/Brunel#166]
I would like to be able to add error bars for the standard deviation (or standard error) around the mean. Something like the following could work to indicate error bars of 2 standard deviations:

`bar x(region) yrange(summer) stddev(summer:2)`

Or 2 standard errors:

`bar x(region) yrange(summer) stderr(summer:2)`

**Comment by danrope** [comment]
Added & used `stderr `for this as in:

`bar x(region) yrange(summer) stderr(summer:2)`
