### ISSUE TITLE
Map graph not working in brunel API

### ISSUE THREAD

**Issue by farman1855** [Brunel-Visualization/Brunel#169]
I use this query in my notbook.

nyvPan = nyvDF.toPandas() %brunel map ('NY') + data('nyvPan') x(lon) y(lat) color(Violations) tooltip(FACILITY)

but it give me this error
`
ValueError: Could not execute Brunel: map ('NY') + data('nyvPan') x(lon) y(lat) color(Violations) tooltip(FACILITY).  Could not read data from: nyvPan(Dataframe)`

**Comment by danrope** [comment]
What language is this notebook?    Also, try placing the creation of nyvPan in a separate cell and confirming its contents.

**Comment by farman1855** [comment]
This Notebook is in python

**Comment by danrope** [comment]
Can you please confirm that `nyvPan` is a pandas dataframe?  The report in the error says `Could not read data from: nyvPan(Dataframe)`.  The reference to the name of the pandas dataframe seems strange here.  If possible, can you let me see the notebook if this continues to be a problem?

**Comment by danrope** [comment]
I tried to replicate the problem on DSX using a python 2 notebook with Spark 1.6.  When I do not convert the dataframe to pandas I get a similar error.  When I convert the Spark dataframe to a pandas dataframe, I get a map with points as expected.  I'm happy to look at a sample notebook exhibiting the issue, but closing this ticket for now.
