### ISSUE TITLE
Export Button

### ISSUE THREAD

**Issue by grahamwills** [Brunel-Visualization/Brunel#17]
"Embed this visualization" works for the straight embedding, but does not work for a link, and I find I often need some more details. There's a lot we could do, but I suggest we have a button which brings up a dialog with the HTML in the bottom and the following options at the top:
 * [check box] embed full visualization as an iframe (what we have now)
 * [check box] generate HTML link with this title (edit box with "brunel visualization" as the default title)
 * [check box] generate caption with brunel script (tagging it as 'code' and 'small' works well for this)
 * [edit box] title ("Brunel Visualization" default, if not defined on page)
 * [edit box] description (none if not defined on page)

**Comment by danrope** [comment]
How about another option here to copy the resulting JS?  This would supply the javascript that Brunel generated for pasting into a self-contained web page (no service calls).

**Comment by grahamwills** [comment]
yes, that would be good. agree

**Comment by danrope** [comment]
Added all suggested features in new UI.
