### ISSUE TITLE
Interactive Network Plots Appear Broken

### ISSUE THREAD

**Issue by renzsickle** [Brunel-Visualization/Brunel#175]
I am currently trying to build an interactive edge + network plot in a Jupyter notebook using Brunel. Unfortunately, when I add an interaction(select:click) to the plot (or a shared plot) and click on a node the network graph breaks. I have been able to replicate this behaviour on the examples at http://brunel.mybluemix.net/docs/ and have attached screenshots.

![brunelnetworkselection1](https://cloud.githubusercontent.com/assets/23272840/20028397/610e2632-a384-11e6-9aba-c7a2ee987ce8.png)
![brunelnetworkselection2](https://cloud.githubusercontent.com/assets/23272840/20028398/611162ca-a384-11e6-8719-275f64f5f340.png)

**Comment by grahamwills** [comment]
Selection was causing a graph layout rebuild which was not correctly attached to the underlying (new) graph structure. This has been fixed on the 'develop' branch, but I am slightly worried with issue with filtered graphs. However this solves the simpler cases and is definitely better.
