### ISSUE TITLE
Spark 2.0 support missing

### ISSUE THREAD

**Issue by torsstei** [Brunel-Visualization/Brunel#176]
Using Spark 2.0 through Apache Toree kernel it seems that there is some issue with the DataFrame API. The %%brunel cell magic does reveal the full stack traces only this:

Magic brunel failed to execute with error: 
org.apache.spark.sql.DataFrame

I assume this is maybe a class cast exception. Maybe brunel jar just needs to be built with Spark 2.0?

**Comment by danrope** [comment]
Currently planning on supporting Spark 2.0 beginning with Brunel 2.2.   Feedback wanted if Spark 1.6 support is still required.

**Comment by danrope** [comment]
Starting with Brunel 2.2 we will support Spark 2.0 in the scala notebook integration.  Prior versions of Spark will no longer be supported.
