### ISSUE TITLE
Root node of tree diagram is defined as "leaf" type in version 2.2 

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#177]
With syntax tree(prune), the root node is defined as "leaf" in version 2.2.

<g class="diagram tree hierarchy">
   <circle class="leaf element point" role="img" aria-label="?, ?, ?, ?, ?, ?" cx="10" cy="217.375" r="7.272389899936141"></circle>
......
</g>

With the identical syntax and data, in version 2.1, the root element was defined as 
<circle class="element L0" role="img" aria-label="?, ?, ?, ?, ?, ?" cx="10" cy="217.375" r="7.272389899936141"></circle>  --- which is correct.

**Comment by grahamwills** [comment]
fixed on develop
