### ISSUE TITLE
D3 exceptions when SVG is hidden

### ISSUE THREAD

**Issue by lkittock** [Brunel-Visualization/Brunel#178]
When I hide a div with a Brunel generated chart in it (e.g. <div style="display: none;">), I get a number of D3 errors, such as this:

    Error: <rect> attribute width: A negative value is not valid. ("-119")

The Brunel build should be aborted if the SVG is hidden or too small.

**Comment by grahamwills** [comment]
If the div has size zero, it is now checked for an explicit height or width attribute which is used to lay out the elements
