### ISSUE TITLE
Builder: Consolidate controls

### ISSUE THREAD

**Issue by grahamwills** [Brunel-Visualization/Brunel#18]
With the other enhancements, our layout will start to look disconnected -- we already have controls in multiple places and this will make them worse. Might be time to add a control panel? I

Whatever is easiest in the UI package to consolidate the space:
 * panel that slides in from side
 * accordion at bottom
 * link that opens a dialog (beside "brunel docs"?)

Move in the following controls (some might be new):
 * width, height
 * set title, set description

**Comment by danrope** [comment]
Addressed with UI redesign
