### ISSUE TITLE
Collapse trees to only show branches leading up to specific leaf node

### ISSUE THREAD

**Issue by lkittock** [Brunel-Visualization/Brunel#180]
I would like a way to collapse all branches on a tree except for the ones leading to a specific leaf node, so I can concentrate on just the nodes/branches leading up to the leaf.

**Comment by grahamwills** [comment]
I enabled a feature on develop to allow this: if you add the command interaction(expand) it expands a node clicked on to show it as the root. This cannot be used with pruning (they are exclusive). If you SHIFT-click on any node, it restores the state to what it was before (or maybe to the default view?)

Try it out and see what you think  and add any comments to this issue

**Comment by grahamwills** [comment]
This interactivity is the same as requested in issue #180

**Comment by grahamwills** [comment]
For trees, you can specify `interaction(expand)` which replaces the default `interaction(collapse)` functionality. In the `expand` case, double-clicking on a  node will make it the root of the tree, hiding everything except its descendants. shift-double-clicking OR double-clicking on the root node will undo a step in the expand sequence.

**Comment by grahamwills** [comment]
feature available on `develop` branch until end of milestone
