### ISSUE TITLE
So many exceptions when using tree(prune) syntax 

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#182]
Data: SynxtheticTree.csv
syntax:    "edge key(Parent, ID) + tree(prune) key(ID) label(Name)"
exceptions: 
    
![image](https://cloud.githubusercontent.com/assets/21226717/20840358/95d91fce-b875-11e6-926d-592ce2726f4f.png)

Tree image: 
![image](https://cloud.githubusercontent.com/assets/21226717/20840400/c1605874-b875-11e6-893d-10ae84b11c3e.png)

PS: without "prune" [  edge key(Parent, ID) + tree  key(ID) label(Name)  ]it is working fine.

**Comment by grahamwills** [comment]
Fixed on develop
