### ISSUE TITLE
filter command doesn't work with "edge"

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#183]
Here is the sample syntax from Brunel Document.pdf:
data('sample:sample_edges.csv') edge key(From, To) opacity(Weight) + data('sample:sample_nodes.csv')network key(Node) size(Count:200%) color(Location) label(Node)

I only want to see the edges which have Weight between [2, 3] so I inserted syntax filter(Weight:[2,]):

data('sample:sample_edges.csv') edge key(From, To) **_filter(Weight:[2, 3])_** opacity(Weight) + data('sample:sample_nodes.csv')network key(Node) size(Count:200%) color(Location) label(Node)

No chart is displayed.

**Comment by danrope** [comment]
Filters now supported with multiple data() statements.  Links are not correctly filtering yet.

**Comment by grahamwills** [comment]
fixed on develop and moving to mater for 2.2 very shortly. It relays out the graph, but has an annoying jerk I'm going to work on later when I have time
