### ISSUE TITLE
tooltip() is too far away from the hovered edge

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#184]
With syntax "edge key(From, To) opacity(Weight) tooltip(#all) ", the tooltip is displayed too far away from the hovered edge so it is hard to tell which edge the tooltip belongs when there are multiple edges. See attached screen shot.

![image](https://cloud.githubusercontent.com/assets/21226717/21150130/8e6f51a2-c123-11e6-9ae0-8347b8b90611.png)

**Comment by grahamwills** [comment]
fixed on develop
