### ISSUE TITLE
slider control from filter command doesn't function as expected

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#186]
Please use the following data.
Here is the syntax I am using:
bar x(Predictor) y(Importance) sort(Importance) filter(Importance:[0.05, 0.2])

The initial chart is correct ( only 3 bar is displayed) and the slider is showing up at the bottom of the chart.
![image](https://cloud.githubusercontent.com/assets/21226717/21437176/01df4c0c-c848-11e6-8a13-a0b14669efde.png)

Issue 1. The slider only has one handle and it is at the zero position. I except to see two handles and one is at 0.05 and one is at 0.2 with the min==0.0. and max == 0.8.

When you try to move the handle of the slider --
Issue 2: the handle can only stop at 0.0 or 1.0. ==>no bar or all bars. I expect that the handle can stop at any position and the bars which have he importance value with the range will be displayed.

Predictor,Importance
BDATE, 0.06050094
MINORITY, 0.11543162
SALBEGIN, 0.66978855
JOBCAT, 0.10086945
GENDER, 0.02796327
EDUC, 0
PREVEXP, 0
JOBTIME, 0.02544617

**Comment by danrope** [comment]
Fixed on develop.
