### ISSUE TITLE
Tree labels in corner

### ISSUE THREAD

**Issue by lkitt** [Brunel-Visualization/Brunel#188]
The attached HTML file is an edited version of a tree diagram created by Brunel (I removed a number of rows of data).  When the HTML is opened in Firefox, one or more labels are showing up in the top-left corner of the page.  These should be labels on the branches.

When I look at the generated HTML for the labels, I see there is one with a "y=0" attribute set.  If I remove this the label disappears.  This doesn't occur in Chrome.

[TREEIssue.zip](https://github.com/Brunel-Visualization/Brunel/files/700338/TREEIssue.zip)

**Comment by grahamwills** [comment]
I am finding it hard to reproduce this issue; it may be that changes to the 2.2 build have fixed this -- please try updating to the latest version and see if that makes it work.

**Comment by cjiang-ibm** [comment]
PLEASE NOTE: the problem **ONLY** happens in **Firefox.**

I have latest Brunel jars which I built from the latest codes of Brunel develop branch. I can stll see the problem using FireFox.

**Comment by grahamwills** [comment]
Please switch over to the master branch -- we are currently updating on that

**Comment by cjiang-ibm** [comment]
I finally figured out an easy way to replicate the problem. It is related with the collapsed node.
Steps:
1. open attached html file in FireFox;
2. As you can see, there is NO collapsed node in the tree diagram. Check the second checkbox from left (Display labels on branches). Everything is perfect. 
3. uncheck the second checkbox.
4. Collapsing any  none-leaf node by double clicking it. The collapsed node will have the dotted line like this.
![image](https://cloud.githubusercontent.com/assets/21226717/22163170/57ac649a-df17-11e6-9e75-ac363c0c9dc6.png)

5. Now check the second checkbox from left ((Display labels on branches). Now you will see the problem. 
![image](https://cloud.githubusercontent.com/assets/21226717/22163306/e02d460e-df17-11e6-8096-35f1fdf11a1f.png)

[TreeDiagramTest.zip](https://github.com/Brunel-Visualization/Brunel/files/720341/TreeDiagramTest.zip)

**Comment by grahamwills** [comment]
Fixed at least a class of examples of this
