### ISSUE TITLE
Builder: Layout minor issues (what being married to a graphic designer leads to ...)

### ISSUE THREAD

**Issue by grahamwills** [Brunel-Visualization/Brunel#19]
A bunch of minor things to improve. Thee are suggestions -- any solution that fits the overall purpose works fine.

 * rename "Brunel Docs" to "Documentation"
 * "Fork me on Github" causes title to take up too much space -- make a simple link beside "Brunel Docs" called maybe just "Github"
 * "Drop a CSV file" needs a box around it; div with rounded edges like the "change data" one would be nice
 * "or" needs to align vertically in the center between the two boxes, currently hangs near the top and looks odd
* Move the disclaimer to a dialog accessed by a text link beside "Brunel Docs" and kill the line above it
* "Embed this visualization" need to move. It overlaps the banner and looks odd. Since it is a major feature I'm not sure it would be good to relegate it to the "put beside 'Brunel Docs'" location, which is really for features less likely to be used in regular use. Maybe add it to the bottom flow? 

So a potential re-layout would be to have all the "uncommon use" items as text link beside the "Brunel docs" area, maybe looking like this: "Documentation  |  Show on GitHub  | Legal". Then the bottom layout would be:
 * one line just for edit, as now
 * responsive (as now): change data box, centered "OR", boxed "drop a CSV", Controls button, Embed button

**Comment by danrope** [comment]
Redesigned UI should address most if not all these concerns.
