### ISSUE TITLE
Feature request: provide a way to accept and use user defined "visInstance" name

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#190]
It is required that visInstance has its own unique name (eg: var v = new BrunelVis("visualization") when you have multiple charts in one page. 

Currently D3Builder#endVisSystem(VisItem main) uses hard codes name "v" for all the places which require "visInstance" name, such as line 381:
 controls.writeEventHandler(out, "v"); 

or line 387:
out.add("BrunelD3.animateBuild(v,",  .....

or line 390:
out.add("v.build(");

In our codes, in order to make multiple charts be displayed in one page, we are replacing "v" with our unique id. The codes are messy. 

The string replacement doesn't work in BrunelJQueryControlFactory .make_range_slider(...) any more because it has  "....v .data(null, 0).field( ..".

The best and cleanest solution is that Brunel to provide a way, such as in BuilderOptions.visInstanceName, for users to set vis instance name and Brunel use it to writes out the script.

**Comment by danrope** [comment]
Added new field in BuilderOptions:

`BuilderOptions.visObject`
