### ISSUE TITLE
Map of NY is not precise

### ISSUE THREAD

**Issue by YDnepr** [Brunel-Visualization/Brunel#191]
Dear team!

I am using the Brunel library to visualize a map of the New York city with points on it. Those points are, actually bike parking spots. Unfortunately on a map that Brunel produces points are not on the right places - some of them appear to be in the ocean, but obviously no bike parking is possible there. 

Is there a possibility solve this problem and visualize a precise map of the New York city (preferably with streets) using Brunel?

Here is the code and how the map looks like:
`%%brunel map('NY') + data('top_15_start') x(START_STATION_LONGITUDE) y(START_STATION_LATITUDE) title("Top-15 start stations") `

where the "top_15_start" is a Spark dataFrame with columns (START_STATION_LONGITUDE, START_STATION_LATITUDE)

<img width="670" alt="newyork" src="https://cloud.githubusercontent.com/assets/17947524/22029165/f9629204-dcd9-11e6-8a34-ef6dd80bd553.png">

Hope you can help! :)

**Comment by grahamwills** [comment]
Here's what SHOULD work:

`%%brunel map('NY', high) + data('top_15_start') x(START_STATION_LONGITUDE) y(START_STATION_LATITUDE) title("Top-15 start stations")`

But the issue is that even at the high fidelity level, it's still expecting to draw a map of the east coast, not so zoomed in. I think we'll need a new level of `full` to make this work.

**Comment by grahamwills** [comment]
On investigation, the base maps we are using (Natural Earth) do not support the level of precision needed to show details within cities. For more detail we would need to overlay on top of a map generation system -- that is getting into the realm of complex mapping which we are not trying for with Brunel.

Sorry -- hope you can either live with the inaccuracy or find another mapping solution!
