### ISSUE TITLE
Does not work as Jupyter notebook

### ISSUE THREAD

**Issue by stanislawbartkowski** [Brunel-Visualization/Brunel#193]
jupyter --version
4.2.1

spark-2.1.0-bin-hadoop2.7

Brunel visualization does not work, JavaScript error
<pre>
Javascript error adding output!
SyntaxError: Octal literals are not allowed in strict mode.
See your browser Javascript console for more details.
</pre>
[notebook.zip](https://github.com/Brunel-Visualization/Brunel/files/712745/notebook.zip)

**Comment by danrope** [comment]
I was able to see the graphs in the attached notebook using both Safari and Firefox on a Mac.  Which browser/OS do you see this issue?  Also, if possible can you paste the browser console output as well?

**Comment by stanislawbartkowski** [comment]
The same issue for Chrome and Firefox. I'm running Ubuntu 16.04

On Firefox the error message is a bit more verbose:
<pre>
Javascript error adding output!
SyntaxError: "0"-prefixed octal literals and octal escape sequences are deprecated; for octal literals use the "0o" prefix instead
See your browser Javascript console for more details.
</pre>

Console output from Firefox:
<pre>
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[Więcej informacji]  main.min.js:84
loaded custom.js  sample%20notebook.ipynb:122:15
Default extension for cell metadata editing loaded.  main.min.js:24261:9
Raw Cell Format toolbar preset loaded.  main.min.js:24347:5
Slideshow extension for metadata editing loaded.  main.min.js:24395:9
Korzystanie z Mutation Events jest przestarzałe. Należy używać MutationObserver.  main.min.js:88:7259
Metoda getPreventDefault() jest przestarzała. Należy używać defaultPrevented.  main.min.js:88:12747
actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...  main.min.js:29204:17
Widgets are not available.  Please install widgetsnbextension or ipywidgets 4.0  main.min.js:34110:17
SyntaxError: "0"-prefixed octal literals and octal escape sequences are deprecated; for octal literals use the "0o" prefix instead
Ślad stosu:
.globalEval@http://localhost:8000/user/sb/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:87:4231
.domManip@http://localhost:8000/user/sb/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:88:21389
.append@http://localhost:8000/user/sb/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:88:18980
OutputArea.prototype._safe_append@http://localhost:8000/user/sb/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:20345:13
OutputArea.prototype.append_execute_result@http://localhost:8000/user/sb/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:20372:9
OutputArea.prototype.append_output@http://localhost:8000/user/sb/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:20218:17
OutputArea.prototype.fromJSON@http://localhost:8000/user/sb/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:20819:13
CodeCell.prototype.fromJSON@http://localhost:8000/user/sb/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:21987:13
Notebook.prototype.fromJSON@http://localhost:8000/user/sb/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:27463:13
Notebook.prototype.load_notebook_success@http://localhost:8000/user/sb/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:27832:13
.proxy/i@http://localhost:8000/user/sb/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:87:5486
  main.min.js:20347:13
Session: kernel_created (a6b2cc43-2b03-4a6f-b4ac-d0c15bd66b49)  main.min.js:23547:13
Starting WebSockets: ws://localhost:8000/user/sb/api/kernels/99898e95-6b76-45c7-9e92-e3148f570d86  main.min.js:22833:9
Kernel: kernel_connected (99898e95-6b76-45c7-9e92-e3148f570d86)  main.min.js:22480:13
Kernel: kernel_ready (99898e95-6b76-45c7-9e92-e3148f570d86)
</pre>

I also found the following JavaScript piece of code in the Notebook
<pre>
 "\n",
       "    // Scales //////////////////////////////////////////////////////////////////////////////////////\n",
       "\n",
       "    var scale_x = d3.scaleLinear().domain([5, 35,000003])\n",
       "      .range([0, geom.inner_width]);\n",
       "    var scale_inner = d3.scaleLinear().domain([0,1])\n",
       "      .range([-0.5, 0.5]);\n",
       "    var scale_y = d3.scaleLinear().domain([0,1])\n",
       "      .range([geom.inner_height, 0]);\n",
       "    var base_scales = [scale_x, scale_y];          // Untransformed original scales\n",

</pre>

Maybe this 0000003 is the aforementioned culprit but it is my blind guess only.

**Comment by danrope** [comment]
Filing as bug.  We (likely) need to ensure numbers are not formatted using the JVM's default Locale when writing JS.

**Comment by stanislawbartkowski** [comment]
Yes, it is related to Locale. After changing the Locale to en_US and restarting Jupyter it works as expected.

<pre>
# default locale
root@sb:~# echo $LANG
pl_PL.UTF-8
# change manually
root@sb:~# export LANG=en_US.utf8
# restart Jupyter
</pre>

**Comment by grahamwills** [comment]
We have made some changes to address this issue and this step should no longer be necessary. Thanks
