### ISSUE TITLE
Allow point labels location based on their axis value

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#194]
Here is syntax and data to generate the chart.
 point x(LEVEL) y(POSITION) key(ID) label(LABEL) style('label-location:top;fill-opacity:1; ')

ID,LEVEL,POSITION,LABEL,FieldName,ImportanceValue,NodeType
0,A,-7,BP=HIGH,BP,0.2,1
1,A,-6,BP=LOW,BP,0.2,1
2,A,-5,BP=NORMAL,BP,0.2,1
3,A,-4,Cholesterol=HIGH,Cholesterol,0.4,1
4,A,-3,Cholesterol=NORMAL,Cholesterol,0.4,1
5,A,-2,Drug=drugA,Drug,0.1,1
6,A,-1,Drug=drugB,Drug,0.1,1
7,A,0,Drug=drugC,Drug,0.1,1
8,A,1,Drug=drugX,Drug,0.1,1
9,A,2,Drug=drugY,Drug,0.1,1
10,A,3,K,K,0.15,1
11,A,4,Na,Na,0.05,1
12,A,5,Sex=F,Sex,0.13,1
13,A,6,Sex=M,Sex,0.15,1
-1,A,7,Bias,Bias,0,0
14,B,-7,H(1:1),Hidden,1.0,1
15,B,-3.5,H(1:2),Hidden,1.0,1
16,B,0,H(1:3),Hidden,1.0,1
-2,B,3.5,Bias,Hidden,1.0,0
17,C,0,Age,Age,1.0,1

Right now, all the point labels are in the same location, left, top, ....

We are required to have something like this:
![image](https://cloud.githubusercontent.com/assets/21226717/22112796/f2b585e6-de29-11e6-960e-96b26e012002.png)

**Comment by grahamwills** [comment]
At the moment, the CSS style feature is likely the one we would use to make this work; you would have two different label styles and uses a css aesthetic to choose one for each. Currently the css aesthetic does not apply to the labels for points, and I think there is an oder of execution issue, but it's definitely doable. I'll add it as a feature.

**Comment by grahamwills** [comment]
New plan! Use two label statements for two fields and given the text a location corresponding to where you want them to be. By making the labels missing where you don't need then, it shows the effect desired

An example is `x(x) y(y) key(#row) label(L1:top, L2:right) axes(none) + data('raw:a,b;1,7;1,8;2,8;7,9') edge key(a, b)` for the data set:

X,Y,L1,L2
1,-2,Red,
1,-1,Yellow,
1,0,Green,
1,1,Blue,
1,2,Purple,
2,-1,,Alpha
2,0,,Beta
2,1,,Delta
3,-0.5,TRUE,
3,0.5,FALSE,
