### ISSUE TITLE
URGENT: syntax error in newly added "function initialState(selection) { " caused no chart being rendered

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#196]
I just pulled the latest codes from master and built all the jars. In our testbed, no chart could be rendered. The error messages were displayed in the console:

LECanvasTest.html:472 Uncaught SyntaxError: missing ) after argument list
LECanvasTest.html:2221 Uncaught SyntaxError: missing ) after argument list
LECanvasTest.html:2827 Uncaught SyntaxError: missing ) after argument list
LECanvasTest.html:3402 Uncaught SyntaxError: missing ) after argument list
...

All this lines point to a same newly added function in Brunel script:
// Define selection entry operations
        function initialState(selection) {
   ....

Indeed the "semi-colon" was misplaced in the last line of the function " data.xxxxx_f(d)}**_;_** "===>
should be  data.xxxxx_f(d)**_;_**}

**Comment by cjiang-ibm** [comment]
Here is the line which caused this problem:
In file Accessibility.java 
function private static void defineElementLabelFunction(ElementStructure structure, ScriptWriter out, D3LabelBuilder labelBuilder) { 
line 50: 
   out.add("}").endStatement();  needs to be changed to  out.endStatement().add("}");

**Comment by danrope** [comment]
Yep.  That was it.  Thanks!
