### ISSUE TITLE
Feature request: provide way for displaying filtered chart based on filter filed values with user created controls

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#199]
Please provide way for displaying filtered chart based on filter filed values with user created controls. 

For example, in network diagram, we have 10 buttons and each of them represent a filter field value/value range. When you click any of the buttons, the diagram will only display the neurons and connections which have the values in that range.

**Comment by danrope** [comment]
Not planning to do if no longer needed.
