### ISSUE TITLE
Enhancement: handling rules as a chord diagram

### ISSUE THREAD

**Issue by ap-aep** [Brunel-Visualization/Brunel#202]
When displaying the rules (i.e. implying support for direction), it is possible to get rules that have different directions but based on the same categories. E.g.:
Camping equipment -> Outdoor protection with confidence 0.31
Outdoor protection -> Camping equipment with confidence 0.6

Brunel's cord diagram will display either first one or the second one depending on the sorting order in the data set. Some approach is needed to visualize the different associations, but related to the same categories.

**Comment by grahamwills** [comment]
Yes. Actually, I think I will classify this as a defect. The chord chart is currently aggregating all "similar" chords based only on the positional fields. I think this is an error and it should only aggregate if explicitly requested to. In particular the following chart should have arc for each state, and yet they are aggregated, showing both wrong colors and tooltips:

`data('sample:US States.csv') x(region) y(boys_name) chord color(state) tooltip(#all)`

**Comment by grahamwills** [comment]
... and this is a little trickier, since we are currently using the D3 chord diagram as a base, and it explicitly won't handle this case. Which seems ... wrong. I will look at making our own version to handle this.

**Comment by grahamwills** [comment]
I have candidate code that fixes this; will be testing and checking in soon

**Comment by grahamwills** [comment]
Checked in new chord diagram
