### ISSUE TITLE
chord stopped working?

### ISSUE THREAD

**Issue by GuusNC** [Brunel-Visualization/Brunel#203]
I just tried the chord example from page http://brunel.mybluemix.net/docs/
The chord itself is not shown, although most of the script seems to be generated. 
Similar for the example at 
`http://brunel.mybluemix.net/gallery_app/renderer?title=Chord+Chart&brunel_src=data%28%27sample%3Awhiskey.csv%27%29+chord+x%28Country%29+y%28Category%29+color%28%23count%29+tooltip%28%23all%29&description=Category+of+whiskey+produced+by+each+country&width=600&height=600&control_height=0`
The legend is shown, but the chord itself is missing. I did get these chords before the weekend. (In fact, I just did a refresh on one of my open firefox tabs, and the chord disappeared.)
I tested this using Firefox, Chrome and Explorer.

Update: 
In firefox debugger I see error message:
`TypeError: chordData.matrix is not a function`
If I go back to `https://brunelvis.org/js/brunel.2.1.min.js`, the problem goes away.

**Comment by danrope** [comment]
A JS file has been changed which causes the break.  We will address this ASAP.

**Comment by GuusNC** [comment]
And it already works again... Thanks for the quick fix.

**Comment by danrope** [comment]
Thanks for letting us know!  We were just testing the change now..
