### ISSUE TITLE
multiple interaction() commands stopped working in version 2.2 or later

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#206]
from "Try Brunel Visualization" site, open any dataset, copy and paste the following syntax.

bar y(Importance) x(Predictor) transpose sort(Importance)  interaction(call:'MdlVizPredImp.showSelected':click) interaction(call:'MdlVizPredImp.showTooltip':snapx:13) 

Check generated script file by clicking Deploy->Source Code->Try jsfiddle. I expect to see the following pieces but they are not there. This caused showSelected() not being called when you click any bar.

chart.select('rect.overlay')
 ....
.on('click.user', function(d) {
 var c = BrunelD3.closest(merged, 'x', 13 );
 showSelected(c.item, c.target, element, 'x');
})
...
merged  
....
 .on('click.user', function(d) {
	showSelected(d, this, element);
})

**Comment by grahamwills** [comment]
This has been fixed for the 2.3 code; will push to the web later

**Comment by cjiang-ibm** [comment]
I just pulled the latest codes from master and tried. I still did NOT see  ".on('click.user', function(d)". 
Is it the right time for me to pull the codes?

**Comment by grahamwills** [comment]
With the following command, for the US dataset:
`x(Region) y(#count) color(#selection) interaction(call:clickfunction:click, call:snapfunction:snapx:13)`
the resulting syntax does include the following:

chart.select('rect.overlay')                         // Attach handlers to the overlay
          .on('click.user', function(d) {
            var c = BrunelD3.closest(merged, 'x', 13 );
            clickfunction(null, c.target, element, 'xy');
          })
          .on('mousemove.user', function(d) {
            var c = BrunelD3.closest(merged, 'x', 13 );
            snapfunction(c.item, c.target, element, 'x');
          })
          .on('mouseout.user', function(d) {
            var c = BrunelD3.closest(merged, 'x', 13 );
            snapfunction(null, c.target, element, 'x');
          });
        merged                                               // Attach handlers to the element
          .on('click.user', function(d) {clickfunction(d, this, element) })
          .on('mouseover.user', function(d) {snapfunction(d, this, element) })
          .on('mouseout.user', function(d) {snapfunction(null, this, element) });

so it does appear functional in the latest (2.3) build

**Comment by cjiang-ibm** [comment]
hmm. I guess that codes  I pulled from master this morning are not the latest then. 

So where can I get or try this "the latest (2.3) build"?

**Comment by grahamwills** [comment]
they are indeed checked into master. If you check your files and search for the string "version", you should see that they refer to the new version 2.3

**Comment by cjiang-ibm** [comment]
After I clean up all the old classes, out,... folders, I did see the issue was fixed. Thanks!
