### ISSUE TITLE
Cannot access filter field if it is from the second dataset

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#208]
The attached html was generated with two datasets. The filter field "ImportanceValue" was in second dataset as it showed in the html.

I always get this exception from this line
var field = v.data(1).field("ImportanceValue");

![image](https://cloud.githubusercontent.com/assets/21226717/22841138/03a8fe78-ef96-11e6-8fe2-27027e49fbd3.png)

Therefore, the filter slider would not be displayed.
[BrunelTestApp.zip](https://github.com/Brunel-Visualization/Brunel/files/767618/BrunelTestApp.zip)

**Comment by danrope** [comment]
Hi.  Try changing that line to:

`var field = v.data(null,1).field("ImportanceValue");`

API is a little confusing here.  The first argument for the API is a data object and the 2nd is the index.  If both are present, the data is set.  If the data object is null, it returns the existing data object with the corresponding index value.

**Comment by cjiang-ibm** [comment]
We can close this one.  The workaround one Dan provided is working for me.
