### ISSUE TITLE
Bar chart outside range of axis

### ISSUE THREAD

**Issue by GuusNC** [Brunel-Visualization/Brunel#210]
I don't know if this is related to the other issue regarding binning of timestamps. I minimised my input file to this set:
```
datetime,events        
2017-02-16T01:04:18,20 
2017-02-16T02:03:05,1  
2017-02-16T03:04:37,10 
2017-02-16T04:04:21,20 
2017-02-16T05:21:21,8  
2017-02-16T06:04:18,10 
2017-02-16T07:04:43,10 
2017-02-16T08:35:05,1  
2017-02-16T09:04:21,20 
2017-02-16T10:37:52,1  
2017-02-16T11:01:05,5  
2017-02-16T12:43:04,1  
2017-02-16T13:03:56,1  
2017-02-16T14:04:21,20
```
I used a statement like the following
`bar x(datetime) y(events:linear) sum(events)  tooltip(datetime,events)&width=400&height=200`
The width and height at the end are there because I use this in a browser window using the rest interface.
The resulting chart consists of mainly two peaks: one on 02AM and one on 03AM.
If I size and grab the chart, I can see there are also peaks more to the right.
If I remove the three last records from my input file, the graph collapses to a single bar that coincides with the y-axis, and the labels on the x-axis are gone.

**Comment by grahamwills** [comment]
I have been re-working the data pipeline, which includes some major changes, and on the code I am working on, this issue looks resolved, so I expect I have solved it as a byproduct of the current work I'm doing. I expect to check in these changes in a few days

**Comment by grahamwills** [comment]
Fix now checked into master
