### ISSUE TITLE
Feature request: supporting custom maps in Brunel

### ISSUE THREAD

**Issue by ap-aep** [Brunel-Visualization/Brunel#212]
Currently Brunel supports great visualization for maps on the level of countries/states. However there is no support for very detailed maps like maps of boroughs in NYC. It would not make sense to load all possible variations in Brunel, but perhaps loading the custom maps and using them with Brunel would make perfect sense.

Here is an example of geojson for NYC boroughs:
https://github.com/dwillis/nyc-maps/blob/master/boroughs.geojson

**Comment by danrope** [comment]
Added ability to use custom topojson.  Instructions are here:  https://github.com/Brunel-Visualization/Brunel/wiki/Custom-Maps
