### ISSUE TITLE
Brunel 2.3 --- axes(x) and axes(y) stopped working 

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#214]
I want to display the axis of Importance and hide the axis of Predictor. Here is the syntax I used:
bar x(Predictor) y(Importance:linear) sort(Importance) axes(y) transpose

The axis of Predictor is still showing up.

**Comment by danrope** [comment]
Code was added today to fix this issue on 2.3.  Can you pull & try again?

**Comment by cjiang-ibm** [comment]
YES!!! It is working now. Thanks
