### ISSUE TITLE
Brunel 2.3 --- extra arrow images were displayed in Tree diagram when using Chrome.

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#215]
When open attached file in **Chrome** , you will see some extra arrow images which did not exist in Brunel 2.2:
![image](https://cloud.githubusercontent.com/assets/21226717/23628025/91b20c9c-0278-11e7-947a-2c518a82615c.png)

With FireFox, it is working fine.
![image](https://cloud.githubusercontent.com/assets/21226717/23628108/e08a08ce-0278-11e7-9f3f-9d5b99b39003.png)

[test.zip](https://github.com/Brunel-Visualization/Brunel/files/822398/test.zip)

**Comment by grahamwills** [comment]
This is new functionality in 2.3, set as the default as in general arrows are preferable. It can be disabled by styling, as indicated in the changelog

**Comment by cjiang-ibm** [comment]
Here is the paragraph from the changelog:
Edge styling

We now support curves and arrows on edges in network, tree and other charts using them. They can be set with a style symbol command to request that style. The valid symbols are given below:

style("symbol:straight") -- simple straight lines
style("symbol:arrow") -- straight lines with an arrow
style("symbol:curved") -- curved lines with no arrowheads
style("symbol:curvedArrow")-- curved lines with arrowheads



We don't want this arrowheads so I tried "style("symbol:curved") " in my syntax like this:
edge size(LinkStrength:[100%, 600%]) key(Parent, ID) label(Parent, '/', ID) **_style('symbol:curved')_** + tree color(type:[#a00000, yellow]) size(nodeSize:[200%, 150%]) key(ID)

Here is the exceptions I'm getting:
java.lang.IllegalArgumentException: The following requested symbols are unknown: [curved]
	at org.brunel.build.SymbolHandler.getInternalURI(SymbolHandler.java:245)
	at org.brunel.build.SymbolHandler.getSymbolURI(SymbolHandler.java:307)
	at org.brunel.build.SymbolHandler.<init>(SymbolHandler.java:72)
	at org.brunel.build.info.ChartStructure.<init>(ChartStructure.java:98)
	at org.brunel.build.ChartBuilder.build(ChartBuilder.java:68)
	at org.brunel.build.ChartBuilder.build(ChartBuilder.java:48)
	at org.brunel.build.VisualizationBuilder.build(VisualizationBuilder.java:117)
	at com.spss.output.brunel.BrunelSampleApp.main(BrunelSampleApp.java:72)


What is the right syntax to NOT showing the grey arrowhead?

**Comment by grahamwills** [comment]
This was a defect; I have pushed changes that should fix it -- please try again after downloading the latest version

**Comment by cjiang-ibm** [comment]
YES!! it is working! Thanks
