### ISSUE TITLE
Brunel 2.3 --- new syntax "symbol(field:[name1, name2, ...]:uri)" does not work with user defined URI 

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#216]
The new syntax "symbol(field:[name1, name2, ...])" works fine with Brunel defined name:

x(Predictor) y(Importance)  symbol(ML:[thumbUp,plus,person])  // note: thumbUp,plus,person are Brunel basic symbols.

If I use the symbol ids from my own .svg file, the syntax does not work:

x(Predictor) y(Importance) tooltip(#all)  symbol(ML:[thumbUpScale, plusN, personO]:'http://localhost:9000/mdlvr/assets/test/test.svg')

[PI_data.zip](https://github.com/Brunel-Visualization/Brunel/files/825249/PI_data.zip)

**Comment by danrope** [comment]
Our understanding is this is no longer an issue.
