### ISSUE TITLE
Brunel 2.3 --- "style('label-location:left')" and "style('label-location:right')" do NOT work with new "symbol" syntax

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#218]
Please use the following data to see the problem.

1. With this syntax: point x(LEVEL) y(POSITION) label(LABEL) axes(none) style('label-location:left; fill-opacity:1;'), everything is working fine. All the labels are in the left side of the dots.

2. If I add the new syntax "symbol":
  point x(LEVEL) y(POSITION) label(LABEL) axes(none) style('label-location:left; fill-opacity:1;') symbol(ML:[flag,person])

All the labels disappeared from the view because the "x" values are wrong.
<text class="label" dy="0.3em" x="222.5333535766602" y="220.00003725878835" style="text-anchor: end;">Age</text>

ID,LEVEL,POSITION,LABEL,FieldName,ImportanceValue,NodeType,ML
12,A,5,Sex=F,Sex,0.13,1,Categorical
13,A,6,Sex=M,Sex,0.15,1,Categorical
-1,A,7,Bias,Bias,0,0,Scale
14,B,-7,H(1:1),Hidden,1.0,1,Z
15,B,-3.5,H(1:2),Hidden,1.0,1,Z
16,B,0,H(1:3),Hidden,1.0,1,Z
-2,B,3.5,Bias,Hidden,1.0,0,Z
17,C,0,Age,Age,1.0,1,Z

**Comment by grahamwills** [comment]
Hmmm. This seems to work:

`x(longitude) y(latitude) symbol(presidential_choice:[flag, person]) sort(water) label(abbr, ' (', population, ')') top(water:10) axes(y) style('label-location:left')`

I'll check your example, but it seems OK at first glance

**Comment by grahamwills** [comment]
Looking more deeply, I think it is working, but there is an issue with the relative placement for symbols -- seems to be too far offset. Will check out

**Comment by grahamwills** [comment]
yes; the box for the label to be drawn around was being calculated wrongly for symbols -- which are actually shapes within their own mini-coordinate system, complicating things. So I added a fix for that
