### ISSUE TITLE
Word cloud visualization may change shape when the visualization is re-executed

### ISSUE THREAD

**Issue by ap-aep** [Brunel-Visualization/Brunel#221]
The cloud visualization changes its presentation for the same set of words and weights: e.g. you click on a topic and get the corresponding cloud, click on another topic, and click on the first one again - the initial cloud visualization is not the same as the last one, but should be identical

Here is an example of the dashboard that may be used for testing this behavior (please select different topics on the primary chart and observe the changes in shape when returning to original topics):
%%brunel data('topicsContent') bar x(topic) y(weight) color(weight) sort(weight) sum(weight) tooltip(#all) interaction(select) | 
interaction(filter)  cloud color(weight) size(weight) sort(weight) label(word)  
:: width=800, height=500

**Comment by grahamwills** [comment]
I believe this was caused by the same root cause as issue #219; I checked and it seems to be solved after applying that fix. Please re-open if that is not the case
