### ISSUE TITLE
TypeError: Package org.brunel.util.D3Integration.getDatasetNames is not Callable

### ISSUE THREAD

**Issue by jonschull** [Brunel-Visualization/Brunel#224]
when I follow the Brunel Network Graphs example 
https://apsportal.ibm.com/analytics/notebooks/6c76b320-7262-4222-8fc3-1bd22fdd32b3/view?access_token=c5fcd0b2fc030e7c26d5db7de16ffe737c736fd985847d7d607dc4a87570c794

I get this error:

(The example does work at 
https://apsportal.ibm.com/analytics/notebooks/13934f58-df0c-49c7-ae0a-697d612efacf?projectid=35ad910a-8faf-438c-910a-644b682abd42&projectTitle=Brunel%20interactive%20visualizations%20in%20Jupyter%20notebooks )

--
TypeError                                 Traceback (most recent call last)
<ipython-input-2-99f9ff916f80> in <module>()
----> 1 get_ipython().run_cell_magic(u'brunel', u"data('edges') key(From,To) edge + ", u"         data('nodes') network color(Node) key(Node) legends(none) style('fill-opacity:1;size:20px') label(Node)")

/Users/jonschull-MBPR/miniconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_cell_magic(self, magic_name, line, cell)
   2113             magic_arg_s = self.var_expand(line, stack_depth)
   2114             with self.builtin_trap:
-> 2115                 result = fn(magic_arg_s, cell)
   2116             return result
   2117 

<decorator-gen-122> in brunel(self, line, cell)

/Users/jonschull-MBPR/miniconda2/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/Users/jonschull-MBPR/miniconda2/lib/python2.7/site-packages/brunel/magics.pyc in brunel(self, line, cell)
     43         parts = line.split('::')
     44         action = parts[0].strip()
---> 45         datasets_in_brunel = brunel.get_dataset_names(action)
     46         self.cache_data(datasets_in_brunel,datas)
     47         if len(parts) > 2:

/Users/jonschull-MBPR/miniconda2/lib/python2.7/site-packages/brunel/brunel.pyc in get_dataset_names(brunel_src)
     92 
     93 def get_dataset_names(brunel_src):
---> 94     return brunel_util_java.D3Integration.getDatasetNames(brunel_src)
     95 
     96 def cacheData(data_key, data):

/Users/jonschull-MBPR/miniconda2/lib/python2.7/site-packages/jpype/_jpackage.pyc in __call__(self, *arg, **kwarg)
     58 
     59     def __call__(self, *arg, **kwarg):
---> 60         raise TypeError("Package {0} is not Callable".format(self.__name))

TypeError: Package org.brunel.util.D3Integration.getDatasetNames is not Callable

**Comment by danrope** [comment]
Hello.  Can you try restarting the kernel and re-execute the cells to see if this resolves the issue?

**Comment by didnotgetagoodname** [comment]
I get the same error. I'm using Python 3.5 with Spark 2.1 where it occurs

**Comment by grahamwills** [comment]
@jonschull -- is this still an issue, or did restarting the kernel fix it for you?

**Comment by wbratton** [comment]
We are seeing the error 

TypeError: Package org.brunel.util.D3Integration.getDatasetNames is not Callable 

with if jpype.startJVM(jvm, args) is successfully called before %brunel data

The attached file ipynb notebook from IBM Data Science Experience illustrates the problem.  To access the ipynb file, change the file name to Test.Brunel_bug_report.zip and unzip it.
[Test+Brunel_bug_report.zip.txt](https://github.com/Brunel-Visualization/Brunel/files/1380816/Test.Brunel_bug_report.zip.txt)

**Comment by grahamwills** [comment]
The technology we used to use (jpype) to call Java from Python has not kept up to date and we have switched to an alternate form. The latest version in PyPI (2.6.2 as of now) uses a new library and should work in notebooks now. It may take some time for Watson Studio (was Data Science Experience) to incorporate the latest version
