### ISSUE TITLE
Unable to install package, R 3.3, macOS Sierra

### ISSUE THREAD

**Issue by kiefersmith** [Brunel-Visualization/Brunel#227]
Hello!  I seem to be having an issue installing in RStudio.  As per the instructions, I run: `devtools::install_github("Brunel-Visualization/Brunel", subdir="R", ref="v2.2")` ,  but nothing seems to happen and eventually I just have to terminate the command.

Any known solutions to this issue?  Is it just me?

Any help is appreciated; looking forward to learning more about the package!

**Comment by danrope** [comment]
Hello.  Brunel is only supported when using R in Jupyter notebooks.   Some instructions on this are here:  https://github.com/Brunel-Visualization/Brunel/tree/master/R

**Comment by kiefersmith** [comment]
Okay.  I must have been confused by the line:

> Important: Install Brunel Visualization into R using R desktop, not from within IRkernel in Jupyter.

I will make use of the package from within Jupyter.  Thanks!

**Comment by danrope** [comment]
Ah!  So, I have had success installing from R desktop, but I have not tried R studio.  I believe I had an issue once where I needed to ensure R was permitted to access/download externally.  Also, change 2.2 to 2.3 to get the latest release.  (I will update that instruction page)
