### ISSUE TITLE
Feature request: consider missing values as valid values in Brunel range filter 

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#230]
Brunel range filter only supports "&&" operation. In some cases, we need both "&&" and "||". For example, I want the chart displayed with ( (value <= max) && (value >= min)) || (value == 0). Right now, there is no way to do it in Brunel.

With this new feature which is requrested here, we are set 0 as missing then my scenario above will work.

**Comment by grahamwills** [comment]
"keepmissing" option on filters

Filters can now take an additional parameter `keepmissing` that changes the default behavior for missing values in filters. When this parameter is specified, missing values are treated as if they were inside the range. Without this parameter, they are treated as lying outside the range, causing that row to be filtered out.

The syntax is just to add `:keepmissing` on the filter

**Comment by cjiang-ibm** [comment]
I tested in our codes and it is working!!! Thanks
