### ISSUE TITLE
Node labels of Network diagram out of position in FireFox when upgrade Brunel to 2.4

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#232]
Brunel 2.4:
![image](https://cloud.githubusercontent.com/assets/21226717/26321866/37596c56-3eee-11e7-8a2c-14b573d4ced3.png)

Brunel 2.3 -- this is the correct one
![image](https://cloud.githubusercontent.com/assets/21226717/26321905/5bde33cc-3eee-11e7-8ed0-68f7867d3a9e.png)

I'm attaching a html file which is generated from Brunel 2.4. 

[BrunelTestApp.zip](https://github.com/Brunel-Visualization/Brunel/files/1019730/BrunelTestApp.zip)

**Comment by grahamwills** [comment]
When I substitute online links for the local javascript file links in the html file, and remove the local css links, it seems fine with the current 2.4 version. I'll resolve this issue, but if it's still the case, we'll need to get an example that is self-contained to diagnose the issue more
