### ISSUE TITLE
[Spark/Toree] require is not defined

### ISSUE THREAD

**Issue by kalvinnchau** [Brunel-Visualization/Brunel#241]
Using the latest (master brunel) build against toree's master branch (compiled and placed into `lib/toree_2.11-assembly.jar`) and updated the gradle dependency to point to this updated jar.

Uploaded the output `spark-kernel-brunel-all-2.4.jar` and ran `%AddJar -magic spark-kernel-brunel-all-2.4.jar` in the Toree environment.

Ran the smoke-test example code:
```
val seq = (0 until 3).map(i => (i, i)).toSeq
val df = spark.createDataFrame(seq)

seq = Vector((0,0), (1,1), (2,2))
df = [_1: int, _2: int]
Out[2]:
[_1: int, _2: int]
In [2]:

%%brunel data('df') x(_1) y(_2) bar
                'brunel' :...
```

```
VM288:1 Uncaught ReferenceError: require is not defined
    at <anonymous>:1:1
    at PanelLayout.attachWidget (panellayout.js:210)
    at PanelLayout.insertWidget (panellayout.js:113)
    at OutputArea._insertOutput (widget.js:335)
    at OutputArea.onModelChanged (widget.js:172)
    at invokeSlot (index.js:475)
    at Object.emit (index.js:433)
    at Signal.emit (index.js:106)
    at OutputAreaModel._onListChanged (model.js:256)
    at invokeSlot (index.js:475)
```

![image](https://user-images.githubusercontent.com/3486716/27718001-e3869bfc-5cfd-11e7-846d-85b4cb789acd.png)

Not sure if requirejs is missing somewhere, couldn't find any docs about making sure it needs to be installed on the server or if something needs to change client-side. Please let me know, thanks!

**Comment by kalvinnchau** [comment]
Turns out jupyterlab doesn't have `requirejs` by default and does not plan to.
https://github.com/jupyterlab/jupyterlab/issues/1188

Any chance you guys are planning to move to jupyterlab?

**Comment by grahamwills** [comment]
Yeah, this does indeed look like a deficiency in Jupyterlab. I'm not sure why they don't intend to support `requirejs` -- it's a safe and common package. We're definitely not that excited about adding a work-around for environments missing it, so unless they start to support it (which they should!) Brunel and other similar libraries will not be supported for it.
