### ISSUE TITLE
Y Axis Labels Getting Clipped

### ISSUE THREAD

**Issue by dpierucci** [Brunel-Visualization/Brunel#244]
When I create a Brunel visualization with the attached data and Brunel syntax, some of the Y axis labels are getting clipped.

[flights10k_csv.txt](https://github.com/Brunel-Visualization/Brunel/files/1170832/flights10k_csv.txt)

bar x(carrier) y(#count) sort(#count) tooltip(#all)

**Comment by grahamwills** [comment]
fixed on both main and the 2.4 defect branch

**Comment by grahamwills** [comment]
Still has issue with Mac Safari

**Comment by dpierucci** [comment]
Thanks Graham!

**Comment by dpierucci** [comment]
This issue appears to still exist. Please use the following syntax and data to reproduce:

bar x(UniqueCarrier) y(#count) sort(#count) tooltip(#all)

[airline3krows.csv.txt](https://github.com/Brunel-Visualization/Brunel/files/1330317/airline3krows.csv.txt)

**Comment by grahamwills** [comment]
All right; think I have it this time
