### ISSUE TITLE
3D charts

### ISSUE THREAD

**Issue by spmp** [Brunel-Visualization/Brunel#246]
Is there any possibility of 3D charts in Brunel?
Specifically scatter and surface with rotate etc.
What effort on my part would be required to see this happen?

**Comment by grahamwills** [comment]
No; Brunel is not planning to have any true-3D functionality. In general such charts require built-in 3D system support in the browser, and there are no current systems we could build on that do that.

As a visualization designer, I also find very few situations were a 3D chart is a better choice than sets of linked 2D charts outside of physical domains (e.g. where X, Y and Z are true dimensions) so it's not an active area of wok either for Brunel, or indeed the general vis community
