### ISSUE TITLE
Brunel support loading vizxml

### ISSUE THREAD

**Issue by wujiazhong** [Brunel-Visualization/Brunel#247]
Hi, I have an issue that there is chart (vizxml) that generated by viz engine. Now I want to using Brunel to show it in browser. My question is does Brunel support loading .viz and display it?

**Comment by grahamwills** [comment]
No, you would need to construct new Brunel -- maybe you could detect the chart type from the .viz data and then use that to build some parameterized Brunel syntax; I've had success doing that with similar cases -- code like `if (type.equals("barchart")) syntax = "bar x($1) y(#count) sort (#count)` and then fill in the parameters with field names.  Brunel's syntax makes that a very doable thing.
