### ISSUE TITLE
spark-kernel-brunel-all-2.3.jar always load js from internet even set onlin_js=False

### ISSUE THREAD

**Issue by cuericlee** [Brunel-Visualization/Brunel#248]
HI, 

after install spark-kernel-brunel-all-2.2.jar into jupyter notebook, brunel chart always load css/js from https://brunelvis.org/js/. when user has no internet access, brunel show nothing

**Comment by grahamwills** [comment]
I think this may have been fixed incidentally; closing it until someone re-reports it
