### ISSUE TITLE
Need a way to request X and Y axes have the same range

### ISSUE THREAD

**Issue by lkitt** [Brunel-Visualization/Brunel#250]
I am using the square aspect ratio - <strong>rectangular(aspect:1, square)</strong> to get a square chart, but I want my X and Y axes to also have the same range of values.  For example, if I have X values from 0 - 10,  and Y values from 10 - 50, I want both axes to have a range of 0 - 50.

I'm using <strong>guide(y:x)</strong>, and I want this y=x line to go diagonally from one corner to the other.  Currently sometimes the line start and stops someplace other than the corner.

**Comment by grahamwills** [comment]
![issue250example](https://user-images.githubusercontent.com/11200129/32965046-e3e9df58-cb9a-11e7-97b7-02a2aef7a8d8.png)


Added new syntax `rectangular(same)` now requires the X and Y axes to be identical, so they will have the same ranges. When combined with `rectangular(square)` the axes will be the same in terms both of the screen real extent and ranges, so a y=x line will go corner-to-corner

**Comment by grahamwills** [comment]
Added in 2.5
