### ISSUE TITLE
Jupyter on Mac : Java SE 6 requested when import brunel

### ISSUE THREAD

**Issue by sebconort** [Brunel-Visualization/Brunel#252]
Hello,

I am on macOS Sierrea, version 10.12.6.
I use python 3.5, and when I try to import brunel in a Jupyter notebook, a pop up asks me to go back to Java SE 6 (I have Java SE 7) 

What could be the problem?
Thanks

**Comment by grahamwills** [comment]
The technology we used to use (jpype) to call Java from Python has not kept up to date and we have switched to an alternate form. The latest version in PyPI (2.6.2 as of now) uses a new library and should work in notebooks now.
