### ISSUE TITLE
SyntaxError: Octal literals are not allowed in strict mode.

### ISSUE THREAD

**Issue by MarcoPorracin** [Brunel-Visualization/Brunel#255]
So im trying the classic 'Cars' example using brunel un a jupyter notebook and i got this error:

`Javascript error adding output!
SyntaxError: Octal literals are not allowed in strict mode.
See your browser Javascript console for more details.`

`SyntaxError: Octal literals are not allowed in strict mode.
    at OutputArea.append_javascript (outputarea.js:727)
    at OutputArea.append_mime_type (outputarea.js:671)
    at OutputArea.append_execute_result (outputarea.js:472)
    at OutputArea.append_output (outputarea.js:310)
    at OutputArea.fromJSON (outputarea.js:990)
    at CodeCell.fromJSON (codecell.js:533)
    at Notebook.fromJSON (notebook.js:2573)
    at Notebook.load_notebook_success (notebook.js:2951)
    at i (jquery.min.js:4)
    at <anonymous>`

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
brunel (2.3)
Google Chrome Versión 60.0.3112.113 (Build oficial) (64 bits)

Any ideas of what could be happening? If more info in needed ask for it.

**Comment by grahamwills** [comment]
It sounds like some javascript is being written with bad numeric formatting; I'll consider this as a defect and see what's up -- if you are able to attach the cars data set as a CSV file, that'd be good just to check out if it's an issue specific to notebooks.

**Comment by grahamwills** [comment]
Can you add the CSV file -- I think i need that to resolve this issue.

**Comment by KrzKusch** [comment]
I'm experiencing the same problem - I tried to run the Cars using Jupyter example as described on:
https://dataplatform.ibm.com/analytics/notebooks/e70491d8-6a7c-4fd3-beaa-86d89cf9d9e7/view?access_token=16e99f8679ebce970a18364bcd5c76702d49865ea7d801e96d081a44b80ed4bc

Then I run a my local dataset and the problem persists - anytime I try to use numeric variable I get error:
Javascript error adding output!
SyntaxError: Octal literals are not allowed in strict mode.
See your browser Javascript console for more details.
