### ISSUE TITLE
Snap should work with tooltips

### ISSUE THREAD

**Issue by lkitt** [Brunel-Visualization/Brunel#256]
I would like the snap feature to work with tooltips, something like this: `tooltip(#all):snap`.  This way if I have really small points, or really thin lines, I can still see the tooltips without much effort in getting the mouse to line up exactly over the point/line.

**Comment by grahamwills** [comment]
added ability to honor snap options in tooltip -- e.g. `tooltip(#all:snap)` and `tooltip(#all:snap:50)` which allow snapping at a default distance and at a syntax-defined distant

**Comment by grahamwills** [comment]
Added in 2.5
