### ISSUE TITLE
snap doesn't work right on points

### ISSUE THREAD

**Issue by lkitt** [Brunel-Visualization/Brunel#257]
Using the "Try it" site http://brunel.mybluemix.net/gallery_app/renderer, I ran this syntax:

data('sample:US States.csv') point x(abbr) y(population) interaction(call:'BrunelD3.crosshairs':mouseover:snapx:3:snapy:3)

I expected that when I got within 3px of any point (vertically or horizontally), I would see the crosshairs.  Instead what happens is whenever my mouse is within 3px of an imaginary vertical line crossing a point, I see crosshairs.

**Comment by grahamwills** [comment]
`snap`, `snapx` and `snap` are mutually exclusive -- only the last one wins, so if you want both x and y, you just use `snap`:

`data('sample:US States.csv') point x(abbr) y(population) interaction(call:'BrunelD3.crosshairs':mouseover:snap:3)`
