### ISSUE TITLE
"slice" support?

### ISSUE THREAD

**Issue by tonycpsu** [Brunel-Visualization/Brunel#261]
I find myself in need of something like ```top()``` and ```bottom()```, but supporting a kind of slice syntax.  E.g. the top 1-10 items is ```top(10)```, but what if I want the next 10 items (11-20)?  I was thinking either something like ```top(10:20)```, or perhaps something like ```slice(10:20:descending)``` to leave the current ```top()``` and ```bottom()``` operators unchanged.

**Comment by grahamwills** [comment]
yes, that is conceptually pretty easy; internally I think both top() and bottom() are implemented using slicing, so might be as simples wiring up some new syntax. I'll look into it

**Comment by tonycpsu** [comment]
OK, while you're in there, I think there might be an off-by-one error in ```bottom()``` -- I'm getting e.g. 26 results with ```bottom(25)```

**Comment by grahamwills** [comment]
I'll check, thanks. It might also be that the bottom values is tied. I might have decided to return both in that case. Now thinking, especially if we implement slice(??:??) that we may just break ties by row order or some other method.

**Comment by tonycpsu** [comment]
FWIW, based on my testing, I don't think it's an issue of ties.

```
foo=pd.DataFrame({"foo": range(100)})

%brunel bar data('foo') x(foo) label(foo) color(foo) top(foo:3) | data('foo') bar x(foo) label(foo) color(foo) bottom(foo:3)
```

**Comment by tonycpsu** [comment]
As for breaking ties, perhaps you could give the user the option to (a) keep all elements of a tied group, (b) use row order to truncate the group, or (c) offer other fields with which to rank on, sort of like a compound sort key, which it appears the ```sort()``` primitive already handles.

**Comment by grahamwills** [comment]
Was indeed an off-by one error. I am adding the new feature, electing to make in an additional option on `top` and `bottom` so that `top(11:20)` will produce the desired ranked items. Adding another numeric parameter to top and bottom seems a good extension.

**Comment by grahamwills** [comment]
Added in 2.5
