### ISSUE TITLE
Request: Invert color maps

### ISSUE THREAD

**Issue by tonycpsu** [Brunel-Visualization/Brunel#264]
Sometimes I'll want to use a color map (e.g. diverging) but I want the map reversed.  As a workaround I'm creating a new column with the values reversed or negated that I only use for the color attribute, but it'd be handy if something like ```color(c:diverging:reverse)``` were supported to avoid the need for this.  I don't see anything in the docs that lets one invert colors the way one can invert axes, sorts, etc.

**Comment by tonycpsu** [comment]
Just figured out I can do ```color(c:[reds,blues])``` as a workaround.

**Comment by grahamwills** [comment]
Yes, Brunel requires that if you don't like the default mappings, you must specify them pretty completely.
