### ISSUE TITLE
Legend Colors Incorrect

### ISSUE THREAD

**Issue by dpierucci** [Brunel-Visualization/Brunel#268]
Please see the following visualization that can be reproduced using the Brunel syntax and data seen below.

The legend items and colors are not correct.

![image](https://user-images.githubusercontent.com/19497430/32007188-71608196-b96e-11e7-8b40-f6b2c1c1df1b.png)

treemap x(Month) color(Year) size(#count) label(count) tooltip(#all) bin(Month) 

[dataviz.txt](https://github.com/Brunel-Visualization/Brunel/files/1415131/dataviz.txt)

**Comment by grahamwills** [comment]
Fixed in 2.5
