### ISSUE TITLE
Line chart: point order was not honored by Brunel

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#269]
Here is the data:
timeVarValuesLine, CumSurvivalLine
0, 1
0.8753, 1
0.8753, 0.98
2.3972603, 0.98 
2.3972603, 0.96
2.8082192, 0.96 
2.8082192, 0.94
4.1890411, 0.94 
4.1890411, 0.92
5.6109589, 0.92 
5.6109589, 0.9

Here is the syntax:
line x(timeVarValuesLine) y(CumSurvivalLine)

Here is the line chart:
![image](https://user-images.githubusercontent.com/21226717/32751996-39e21b2a-c88d-11e7-8651-95da3802cd42.png)

****** Additional information ****
If I remove the last two rows from the data and re-run the syntax, the chart is going to be right, like this:
![image](https://user-images.githubusercontent.com/21226717/32752145-ba99c150-c88d-11e7-99b0-e95a057b5f59.png)

**Comment by grahamwills** [comment]
[issue269.txt](https://github.com/Brunel-Visualization/Brunel/files/1482931/issue269.txt)
is a CSV file with the data

**Comment by grahamwills** [comment]
Fixed in 2.5
