### ISSUE TITLE
Bar chart --- sort() command does not work 

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#272]
Here is my data:

NAME,SIZE,LABEL
1 ,10,number_1
2 ,45,number_2
3 ,19,number_3
4 ,67,number_4
5 ,25,number_5

Here is my syntax:
bar x(NAME) y(SIZE) transpose color(LABEL) sort(SIZE) label(LABEL) axes(x:5, y:10)

Here is what I'm getting from http://brunel.mybluemix.net/gallery_app/renderer:

![image](https://user-images.githubusercontent.com/21226717/33081662-70036b0a-cea0-11e7-8973-67d6d5306da0.png)

******** Issue: *******
I expect to see the bar in the order of number_4, number_2, number_5, number_3 and number_1.

**Comment by grahamwills** [comment]
The blue mix service is significantly out of date; please try with the latest build and submit a defect if the issue persists -- attaching the data as a CSV is also very valuable.
