### ISSUE TITLE
Installing latest versions (> 2.3) from pip

### ISSUE THREAD

**Issue by tonycpsu** [Brunel-Visualization/Brunel#276]
I've been installing brunel using pip, but I haven't seen the recent 2.4 or 2.5 versions published there.  Is pip deprecated as a distribution channel for Brunel at this time, or is it just lagging behind a couple of versions?

**Comment by rolweber** [comment]
The latest version on PyPI is still 2.3: https://pypi.python.org/pypi/brunel

@grahamwills: Is updating Brunel on PyPI not part of the release process?

Few Python users will build Brunel from source. Most will run `pip install brunel` and assume to get the latest version that way. Not updating the package on PyPI cuts them off from bug fixes and new features.

**Comment by grahamwills** [comment]
The technology we used to use (jpype) to call Java from Python has not kept up to date and we have switched to an alternate form. The latest version in PyPI (2.6.2 as of now) uses a new library and should work in notebooks now. It took us some time to find and deploy a version that works -- thanks for sticking with us, and please try it out and see how it works; we have only tested under a few configurations

**Comment by tonycpsu** [comment]
@grahamwills: The new version installs fine, but I'm not getting good results from it.  When I import brunel I get a bunch of debug output, which is fine, but then when I try to plot something I get similar debug output and no actual plot.  Here's a screenshot:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/914142/39459481-e4b935a4-4cc9-11e8-82cf-d10918cff839.png">

Will file a separate issue if necessary.

**Comment by tonycpsu** [comment]
OS X.  Python 3.6.5, andJava 1.80, if either of those matter.
