### ISSUE TITLE
When network diagram is hidden, "Uncaught TypeError: Cannot read property 'install' of undefined" will be displayed

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#277]
1. When style="display:none;" is used, the network diagram stopped working and following exceptions can be seen from browser's debugger console:
Uncaught TypeError: Cannot read property 'install' of undefined
    at label (BrunelTestApp.html:192)
    at Object.build (BrunelTestApp.html:203)
    at Object.build (BrunelTestApp.html:399)
    at BrunelTestApp.html:416
    at Array.forEach (<anonymous>)
    at updateAll (BrunelTestApp.html:416)
    at Object.buildAll [as build] (BrunelTestApp.html:419)
    at BrunelTestApp.html:474

2. Here is the html generated by Brunel. I have inserted "<div style=\"display:none;\">" in line 30 for replicating this issue.

3. If you remove the style from line 30, the chart is working without any problem.

[BrunelTestApp.html.zip](https://github.com/Brunel-Visualization/Brunel/files/1553377/BrunelTestApp.html.zip)

**Comment by grahamwills** [comment]
I added a simple fix for this; just a question fo a slightly different execution flow hitting a null value before it tested for it.

Please verify that the fix is in place before I close this. Thanks

**Comment by cjiang-ibm** [comment]
Thanks, Graham!

Should I just pull from the master branch?

Jane

**Comment by cjiang-ibm** [comment]
It is working for us!!!
Thanks for the speedy fix!!!
