### ISSUE TITLE
Brunel in Jupyter Lab

### ISSUE THREAD

**Issue by GraemeHutcheon** [Brunel-Visualization/Brunel#294]
https://github.com/jupyterlab/jupyterlab/issues/3118

It appears in Jupyter Lab you can no longer run adhoc Javascript - see link above.
"JavaScript output is disabled in JupyterLab"
 
Is there a way to use Brunel in Lab ? is there a plan to integrate ?

**Comment by grahamwills** [comment]
I'll check it out, but that sounds worryingly like a showstopper. Very limiting by Jupyter Lab if this is the case

**Comment by grahamwills** [comment]
Yes, I see other interactive views have also been hit by this decision; apparently on a custom user install you can override the default security, but I do not see a path to interactive Javascript in JupyterLab, except by something very custom. I guess JupyterLab is no longer supported.
