### ISSUE TITLE
Resizing chart causes axis label to overwrite tick labels

### ISSUE THREAD

**Issue by lkitt** [Brunel-Visualization/Brunel#299]
I created a chart of size 284 x 284.  It looks like this:
![image](https://user-images.githubusercontent.com/11357071/38899484-a0315ec8-425d-11e8-8026-733ffbd6673c.png)

I then resized the chart (in JavaScript) to be 398 x 398.  It looks like this:
![image](https://user-images.githubusercontent.com/11357071/38899529-bc6a1922-425d-11e8-948f-40045078b11d.png)

Notice the "Predicted" label is on top of the X-axis tick labels.

**Comment by grahamwills** [comment]
I have made a fix to the axis layout code which I *suspect* will help with this. I'm going to mark this as "code pending" and when I commit the 2.6 version with all fixes, we should re-test this and see how it works
