### ISSUE TITLE
Feature request: the data range of axis -- X or/and Y can be changed dynamically

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#303]
There are two use cases from our team:
1. The Y values are calculated based on user inputs.
2. There are multiple charts which are on top of each other with different X range. We want to show the chart one at a time based at run time based on the selection of other controls.

**Comment by grahamwills** [comment]
I have added new functionality to set the scales, plus an example page showing how to use it:

http://brunelvis.mybluemix.net/examples/scales.html


This requires the latest version of Brunel
