### ISSUE TITLE
Brunel 2.6 -- hundreds exceptions when <iframe> is used AND  size() syntax is used.

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#305]
1. With upgrading to Brunel 2.6, there are tons of exceptions displayed one Chrome and Safari. FireFox is fine. See screenshot below:
![screen shot 2018-06-14 at 11 46 40 am](https://user-images.githubusercontent.com/21226717/41426237-aad45874-6fc8-11e8-838f-ab55e4dac9ec.png)

2. The syntax is:
    point x(Predicted:linear) y(Observed:linear) size(Frequency:[100%, 800%)
3. Data attached.
4. If you remove siz() syntax, everything is working fine.

Please try this link which has <iframe> to see the exceptions:
https://ys1.us-south.containers.mybluemix.net/dev/mv/mdlvr/assets/html/testbed_v3.html 
just click "Show Model Visualization" button.

[ObservedByPredict.csv.zip](https://github.com/Brunel-Visualization/Brunel/files/2103267/ObservedByPredict.csv.zip)

**Comment by grahamwills** [comment]
It looks like there is an issue in how the data is being added or maybe manipulated in the code.
When I look at the Javascript generated it sets the scale for the size like so:

`var scale_size = d3.scaleSqrt().domain([18166, 135001.0116835])`

The domain indicates the values are expected to be in the range 18K -> 135K
But if you look at the data table, it has frequency values in the range 1 -> 33 or so; very different.
So I think the root problem is that something is happening when you generate the javascript that makes the frequency look like one of the other variables. I am not sure this is an i-frame issue.

If you do find this still to be an issue, please try and create an example with a html file and iframe pointing to a single chart that shows the issue, and then re-open this issue. Thanks
