### ISSUE TITLE
Brunel 2.6 -- syntax  "x(field1:[min,max]) y(field2:[min,max])" cannot co-exist with size(field3:[100%, 800%])

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#308]
Running this syntax will generate tons of exceptions:
   point x(Predicted:[18166.0, 135001]:linear) y(Observed:[18166.0, 135001]:linear) size(Frequency:[100%, 800%])

If you remove the size() or remove the range --[18166.0, 135001], the chart will display correctly without any problem.

You can try to run the syntax using the data from attached zip using http://brunelvis.mybluemix.net/try.html. Please use Safari or Chrome to see the exceptions.

Then open console window when inspect. You will see:

![screen shot 2018-06-20 at 10 54 17 am](https://user-images.githubusercontent.com/21226717/41669912-85525542-7478-11e8-93f8-0aeae66026f4.png)

[showexceptions.zip](https://github.com/Brunel-Visualization/Brunel/files/2120131/showexceptions.zip)

**Comment by grahamwills** [comment]
The previous issue appeared to be with data incorrectly written; the data used to generate the Javascript appeared significantly different from the data used in the JS (specifically the Frequency column). Please validate that the data for frequency being passed to Java is identical to that being used in the Javascript.

**Comment by cjiang-ibm** [comment]
Sorry, if I was not very clear before.

There are 3 fields in the data --- Predicted,  Observed and Frequency. 
The range is for X(Predicted) and Y(Observed) -- [18166.0, 135001]
The size is for Frequency.

**Comment by grahamwills** [comment]
Yes. The problem is that when the javascript is being generated the frequency column appears to have *different* data in it. Please debug the application and check that, when the visualization builder is working, that the values of frequency are in the range 1 ... 91. Based on the Javascript output, that does not appear to be the case

**Comment by cjiang-ibm** [comment]
The problem can be replicated using Brunel's own online app by following the steps below:
 
1. Open try brunel  by clicking this link: http://brunelvis.mybluemix.net/try.html
2. Click Data Table tab and remove all the default data. 
3. Open ObservedByPredict.csv from the attached .zip file and copy the entire content to Data Table tab.
![screen shot 2018-06-20 at 2 46 27 pm](https://user-images.githubusercontent.com/21226717/41681031-06042178-7499-11e8-9523-ac668e70ed81.png)

3. Click "Brunel Syntax" tab and remove the default syntax;
4. Open file syntaxWithSizeAndRange.txt from the attached zip and copy the entire content to "Brunel Syntax" tab.
![screen shot 2018-06-20 at 2 51 37 pm](https://user-images.githubusercontent.com/21226717/41681195-7bc28a26-7499-11e8-97fe-293577a9ffc3.png)

5. Click "Build" button, you will see the point chart displayed
6. from the chart panel, right click and select "Inspect" from the context menu and click "Console". Here is what is inside console:
![screen shot 2018-06-20 at 2 55 40 pm](https://user-images.githubusercontent.com/21226717/41681373-0bafc98c-749a-11e8-8a2e-cc9d276298c7.png)

**Comment by grahamwills** [comment]
Thanks! That is very helpful

**Comment by cjiang-ibm** [comment]
fixed!
