### ISSUE TITLE
Galery doesn't work

### ISSUE THREAD

**Issue by dmitriyshashkin** [Brunel-Visualization/Brunel#320]
http://brunel.mybluemix.net/gallery_app/renderer?title=Treemap&brunel_src=data%28%27sample%3ABGG+Top+2000+Games.csv%27%29+treemap+x%28Language%2C+Categories%29+color%28PlayerAge%3Acontinuous%29+size%28Rating%29+label%28%22Rating%3A+%22%2C+Rating%29+mean%28PlayerAge%2C+Rating%29&description=Game+category+within+median+%27language+used%27+sized+by+average+game+rating+and+colored+by+average+player+age.&width=800&height=600&control_height=0

Error! Could not execute Brunel: data('sample:BGG Top 2000 Games.csv') treemap x(Language, Categories) color(PlayerAge:continuous) size(Rating) label("Rating: ", Rating) mean(PlayerAge, Rating)Could not execute Brunel: data('sample:BGG Top 2000 Games.csv') treemap x(Language, Categories) color(PlayerAge:continuous) size(Rating) label("Rating: ", Rating) mean(PlayerAge, Rating)
null

I get the same result with other examples from the galery

**Comment by grahamwills** [comment]
I have switched to a new server on bluemix -- please try the following top-level access url:

http://brunelvis.mybluemix.net

If you go to the try tab, you should be able to paste in `data('sample:BGG Top 2000 Games.csv') treemap x(Language, Categories) color(PlayerAge:continuous) size(Rating) label("Rating: ", Rating) mean(PlayerAge, Rating)` and immediately see the result.

Thanks!
