### ISSUE TITLE
Support Sun 1.8 JDK

### ISSUE THREAD

**Issue by mpierre0220** [Brunel-Visualization/Brunel#33]
Currently experiencing several problems when using Sun JDK v1.8. Graham Willis is aware of the probem and will fix it using this issue number.

**Comment by grahamwills** [comment]
Turned out to be issues with encoding and required python test framework that is hard to install and doesn't work automatically. Fixed the encoding and commented out the python tests pending a simpler solution for developers

**Comment by mpierre0220** [comment]
Hi Graham,

	I have deployed Brunel and successfully compiled and ran the sample
Java application. I am confident that new users of Brunel will be able to
do the same. I am thinking of writing a blog for newbies as well.

	On a different topic. Currently Brunel is using D3 by default. Given
that we're also interested in Rave 2, I am wondering if you could point me
to any document that details how one can switch from D3 to Rave 2 while
using Brunel. Please let me know.

Best regards,

Marc-Arthur Pierre-Louis
Software Design & Development (Advanced Technology and Design)
e-mail: mpierre@us.ibm.com
(704)340-9217
There are people who make history; there are those made by history. The
latter must return the favor if the cycle of life must continue since it is
by creating them that history recreates itself.
Il y a des gens qui font l'histoire; il y en a que fait l'histoire. Ces
derniers doivent lui rendre la réciprocité si le cycle de vie doit
continuer. C'est en les créant que l'histoire se recrée.
Marc-Arthur Pierre-Louis
