### ISSUE TITLE
Test failed at StyleSheetTest

### ISSUE THREAD

**Issue by nqbao** [Brunel-Visualization/Brunel#38]
I have a problem when running `gradle check` on my local, it fails with the below exception

```
org.brunel.model.style.StyleSheetTest > testWriting FAILED
    org.junit.ComparisonFailure at StyleSheetTest.java:38
```

```
org.junit.ComparisonFailure: expected:<a {
	[y: 2;
	x: 1;
}

.c {
	z: 4;
	x: 2];
}
> but was:<a {
	[x: 1;
	y: 2;
}

.c {
	x: 2;
	z: 4];
}
>
```

Is it intended? I'm using java8 for testing, is it a possible problem?

My gradle version

```
------------------------------------------------------------
Gradle 2.5
------------------------------------------------------------

Build time:   2015-07-08 07:38:37 UTC
Build number: none
Revision:     093765bccd3ee722ed5310583e5ed140688a8c2b

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.11 x86_64
```
Please help. Thanks!

**Comment by grahamwills** [comment]
There was an issue where we were depending on the order of keys in a map when writing out the style sheet properties. This made no difference in practice, but does cause the test failure you noticed when running on a system with a different JVM. 

We did fix this issue a few days ago; if you pull the latest version, it now sorts explicitly and so the test passes, with the keys in alphabetical order.

To check you version, here is a link to the latest (corrected) test:

https://github.com/Brunel-Visualization/Brunel/blob/master/core/src/test/java/org/brunel/model/style/StyleSheetTest.java

**Comment by nqbao** [comment]
:+1: work perfectly now
