### ISSUE TITLE
using(interpolate) fails

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#39]
This can be observed in the tutorial page "Basic Concepts":

Selecting:
line x(winter) y(summer) color(region) using(interpolate) legends(none)

Gives a blank graph.  Remove using(interpolate) and the line appears.

**Comment by grahamwills** [comment]
Should be fixed in next build. Not 100% happy with the choice of D3 interpolate function, but do not want to write our own right now ...

**Comment by danrope** [comment]
Fix has been pushed to live docs.
