### ISSUE TITLE
Browser Compatibility: FireFox

### ISSUE THREAD

**Issue by grahamwills** [Brunel-Visualization/Brunel#4]
It appears the major issue is related to text, but this issue is to make sure everything looks as good under FF as in any other Browser

**Comment by danrope** [comment]
* Selection Currently Failing.  See "Interactive linked state charts" on wiki.  Selection works 1st time only.

**Comment by grahamwills** [comment]
The selection failing was actually a text issue also -- it starts doing the selection, draws one text items and then dies. On investigation FF apparently straight up does not support getting bounding boxes of text spans, instead replacing the method with one that throws an error. Checking in a  change that works around that issue.
