### ISSUE TITLE
Labels missing on pie chart cookbook example

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#41]
The labels for the cookbook pie chart example seem to have disappeared:

http://brunel.mybluemix.net/gallery_app/renderer?title=Pie+Chart&brunel_src=data%28%27sample%3AUS+States.csv%27%29+stack+polar+bar+x%28%22const%22%29+y%28%23count%29+color%28region%29+legends%28none%29+label%28region%29&description=Proportion+of+number+of+states+in+each+region&width=400&height=400&control_height=0

Should have the regions labeled on the pie slices.

**Comment by grahamwills** [comment]
Path was not being added to labeling object; will be fixed in next build

**Comment by danrope** [comment]
Change pushed.  Bug gone.
