### ISSUE TITLE
Aesthetic Mappings & 0.8 implementation

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#42]
Decide on Aesthetic Mapping strategy and ensure 0.8 is future-compatible with the strategy.

Proposal is here:
https://github.com/Brunel-Visualization/Brunel/wiki/Proposal:--Aesthetic-Mappings

**Comment by grahamwills** [comment]
Changes added for 0.8 which are compatible with the approaches in the wiki. Take a look and close this issue if it seems correct

**Comment by danrope** [comment]
Looks good.
