### ISSUE TITLE
Empty Charts:  Failure to locate .js and .css in certain Jupyter environments

### ISSUE THREAD

**Issue by GraemeHutcheon** [Brunel-Visualization/Brunel#44]
I have just installed brunel and any chart I create is blank.
From the Console I see the attached messages.
I tried Chrome, Safari & FF. Installed and Installed --local, all have same outcome.
Any advice would be great
![screen shot 2015-11-24 at 7 39 58 am](https://cloud.githubusercontent.com/assets/15999103/11367108/89d6a25e-927f-11e5-8f4b-ceed4c284643.jpg)

**Comment by danrope** [comment]
Hello.  Sorry you are having problems.  We have seen issues with the pip install in different environments.  Usually this has been observed when using different local accounts on the same machine.    When you say "--local" above, do you mean that "pip install --user" also fails similarly?  If so, can you share a little more about your environment?  Which python/version, ipython/version, is your environment single user or shared, etc.  Thanks.

**Comment by GraemeHutcheon** [comment]
Yes - pip install --user.
I am running Mac 0Sx - Anaconda with Python 3.5, Should be single user.
Are there any commands I can run to get you more specifics.

This is from the About menu in Python.

![screen shot 2015-11-24 at 8 31 03 am](https://cloud.githubusercontent.com/assets/15999103/11368138/01cf6c68-9286-11e5-8ce9-70f32ed26e24.jpg)

**Comment by danrope** [comment]
Thanks.  Another question..  In your browser console.  Is it failing to find several 'brunel' .js files or just the two .css files in the picture above?  (the 404 not found errors)?

**Comment by GraemeHutcheon** [comment]
When I run that cars script and ask Brunel to draw the chart it's only those two css.
I was clicking on other stuff and then saw some error about not finding brunel .js from that /nbextensions/brunel_ext/ directory.

**Comment by danrope** [comment]
Thank you.  I am classifying this as a bug.  We will try to get this fixed as soon as possible.

**Comment by GraemeHutcheon** [comment]
I decide to clean everything and install once more from scratch - this ends up with an error in the log which appear to point to the same directory mentioned in the web dialog above.

Sorry for this - 

Collecting brunel
  Using cached brunel-0.8.0.zip
Requirement already satisfied (use --upgrade to upgrade): pandas in /Users/v2graeme/anaconda/lib/python3.5/site-packages (from brunel)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /Users/v2graeme/anaconda/lib/python3.5/site-packages (from brunel)
Requirement already satisfied (use --upgrade to upgrade): ipython in /Users/v2graeme/anaconda/lib/python3.5/site-packages (from brunel)
Requirement already satisfied (use --upgrade to upgrade): jupyter-pip in /Users/v2graeme/.local/lib/python3.5/site-packages (from brunel)
Requirement already satisfied (use --upgrade to upgrade): JPype1-py3 in /Users/v2graeme/.local/lib/python3.5/site-packages (from brunel)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2 in /Users/v2graeme/anaconda/lib/python3.5/site-packages (from pandas->brunel)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in /Users/v2graeme/anaconda/lib/python3.5/site-packages (from pandas->brunel)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.0 in /Users/v2graeme/anaconda/lib/python3.5/site-packages (from pandas->brunel)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /Users/v2graeme/anaconda/lib/python3.5/site-packages (from jinja2->brunel)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /Users/v2graeme/anaconda/lib/python3.5/site-packages (from python-dateutil>=2->pandas->brunel)
Building wheels for collected packages: brunel
  Running setup.py bdist_wheel for brunel
  Complete output from command /Users/v2graeme/anaconda/bin/python3 -c "import setuptools;__file__='/private/var/folders/sm/vn7jghs93x718m365s9n882m0000gn/T/pip-build-q8w747qr/brunel/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/sm/vn7jghs93x718m365s9n882m0000gn/T/tmp690qi48dpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/brunel
  copying brunel/__init__.py -> build/lib/brunel
  copying brunel/brunel.py -> build/lib/brunel
  copying brunel/brunel_util.py -> build/lib/brunel
  copying brunel/brunelWidgets.py -> build/lib/brunel
  copying brunel/magics.py -> build/lib/brunel
  running egg_info
  writing requirements to brunel.egg-info/requires.txt
  writing dependency_links to brunel.egg-info/dependency_links.txt
  writing brunel.egg-info/PKG-INFO
  writing top-level names to brunel.egg-info/top_level.txt
  /Users/v2graeme/anaconda/lib/python3.5/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
    "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'brunel.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'brunel.egg-info/SOURCES.txt'
  copying brunel/D3_Template.html -> build/lib/brunel
  copying brunel/D3_Template.js -> build/lib/brunel
  creating build/lib/brunel/brunel_ext
  copying brunel/brunel_ext/BrunelBaseStyles.css -> build/lib/brunel/brunel_ext
  copying brunel/brunel_ext/BrunelD3.js -> build/lib/brunel/brunel_ext
  copying brunel/brunel_ext/BrunelData.js -> build/lib/brunel/brunel_ext
  copying brunel/brunel_ext/BrunelEventHandlers.js -> build/lib/brunel/brunel_ext
  copying brunel/brunel_ext/BrunelJQueryControlFactory.js -> build/lib/brunel/brunel_ext
  copying brunel/brunel_ext/BrunelWidgets.js -> build/lib/brunel/brunel_ext
  creating build/lib/brunel/brunel_ext/sumoselect
  copying brunel/brunel_ext/sumoselect/jquery.sumoselect.min.js -> build/lib/brunel/brunel_ext/sumoselect
  copying brunel/brunel_ext/sumoselect/sumoselect.css -> build/lib/brunel/brunel_ext/sumoselect
  creating build/lib/brunel/lib
  copying brunel/lib/brunel-core-0.8.jar -> build/lib/brunel/lib
  copying brunel/lib/brunel-data-0.8.jar -> build/lib/brunel/lib
  copying brunel/lib/gson-2.3.1.jar -> build/lib/brunel/lib
  installing to build/bdist.macosx-10.5-x86_64/wheel
  running install
  Installing Python module...
  running install_lib
  creating build/bdist.macosx-10.5-x86_64
  creating build/bdist.macosx-10.5-x86_64/wheel
  creating build/bdist.macosx-10.5-x86_64/wheel/brunel
  copying build/lib/brunel/__init__.py -> build/bdist.macosx-10.5-x86_64/wheel/brunel
  copying build/lib/brunel/brunel.py -> build/bdist.macosx-10.5-x86_64/wheel/brunel
  creating build/bdist.macosx-10.5-x86_64/wheel/brunel/brunel_ext
  copying build/lib/brunel/brunel_ext/BrunelBaseStyles.css -> build/bdist.macosx-10.5-x86_64/wheel/brunel/brunel_ext
  copying build/lib/brunel/brunel_ext/BrunelD3.js -> build/bdist.macosx-10.5-x86_64/wheel/brunel/brunel_ext
  copying build/lib/brunel/brunel_ext/BrunelData.js -> build/bdist.macosx-10.5-x86_64/wheel/brunel/brunel_ext
  copying build/lib/brunel/brunel_ext/BrunelEventHandlers.js -> build/bdist.macosx-10.5-x86_64/wheel/brunel/brunel_ext
  copying build/lib/brunel/brunel_ext/BrunelJQueryControlFactory.js -> build/bdist.macosx-10.5-x86_64/wheel/brunel/brunel_ext
  copying build/lib/brunel/brunel_ext/BrunelWidgets.js -> build/bdist.macosx-10.5-x86_64/wheel/brunel/brunel_ext
  creating build/bdist.macosx-10.5-x86_64/wheel/brunel/brunel_ext/sumoselect
  copying build/lib/brunel/brunel_ext/sumoselect/jquery.sumoselect.min.js -> build/bdist.macosx-10.5-x86_64/wheel/brunel/brunel_ext/sumoselect
  copying build/lib/brunel/brunel_ext/sumoselect/sumoselect.css -> build/bdist.macosx-10.5-x86_64/wheel/brunel/brunel_ext/sumoselect
  copying build/lib/brunel/brunel_util.py -> build/bdist.macosx-10.5-x86_64/wheel/brunel
  copying build/lib/brunel/brunelWidgets.py -> build/bdist.macosx-10.5-x86_64/wheel/brunel
  copying build/lib/brunel/D3_Template.html -> build/bdist.macosx-10.5-x86_64/wheel/brunel
  copying build/lib/brunel/D3_Template.js -> build/bdist.macosx-10.5-x86_64/wheel/brunel
  creating build/bdist.macosx-10.5-x86_64/wheel/brunel/lib
  copying build/lib/brunel/lib/brunel-core-0.8.jar -> build/bdist.macosx-10.5-x86_64/wheel/brunel/lib
  copying build/lib/brunel/lib/brunel-data-0.8.jar -> build/bdist.macosx-10.5-x86_64/wheel/brunel/lib
  copying build/lib/brunel/lib/gson-2.3.1.jar -> build/bdist.macosx-10.5-x86_64/wheel/brunel/lib
  copying build/lib/brunel/magics.py -> build/bdist.macosx-10.5-x86_64/wheel/brunel
  running install_egg_info
  Copying brunel.egg-info to build/bdist.macosx-10.5-x86_64/wheel/brunel-0.8.0-py3.5.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: '/Users/v2graeme/.local/lib/python3.5/site-packages/jupyterpip/brunel/brunel_ext'
  Installing nbextension ...
  copying /Users/v2graeme/.local/lib/python3.5/site-packages/jupyterpip/brunel/brunel_ext -> /Users/v2graeme/Library/Jupyter/nbextensions/brunel_ext
  
  ----------------------------------------
  Failed building wheel for brunel
Failed to build brunel
Installing collected packages: brunel
  Running setup.py install for brunel
    Complete output from command /Users/v2graeme/anaconda/bin/python3 -c "import setuptools, tokenize;__file__='/private/var/folders/sm/vn7jghs93x718m365s9n882m0000gn/T/pip-build-q8w747qr/brunel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/sm/vn7jghs93x718m365s9n882m0000gn/T/pip-bxxle1di-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    Installing Python module...
    running build
    running build_py
    running egg_info
    writing requirements to brunel.egg-info/requires.txt
    writing brunel.egg-info/PKG-INFO
    writing top-level names to brunel.egg-info/top_level.txt
    writing dependency_links to brunel.egg-info/dependency_links.txt
    /Users/v2graeme/anaconda/lib/python3.5/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
      "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'brunel.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'brunel.egg-info/SOURCES.txt'
    running install_lib
    creating /Users/v2graeme/.local/lib/python3.5/site-packages/brunel
    copying build/lib/brunel/__init__.py -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel
    copying build/lib/brunel/brunel.py -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel
    creating /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/brunel_ext
    copying build/lib/brunel/brunel_ext/BrunelBaseStyles.css -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/brunel_ext
    copying build/lib/brunel/brunel_ext/BrunelD3.js -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/brunel_ext
    copying build/lib/brunel/brunel_ext/BrunelData.js -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/brunel_ext
    copying build/lib/brunel/brunel_ext/BrunelEventHandlers.js -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/brunel_ext
    copying build/lib/brunel/brunel_ext/BrunelJQueryControlFactory.js -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/brunel_ext
    copying build/lib/brunel/brunel_ext/BrunelWidgets.js -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/brunel_ext
    creating /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/brunel_ext/sumoselect
    copying build/lib/brunel/brunel_ext/sumoselect/jquery.sumoselect.min.js -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/brunel_ext/sumoselect
    copying build/lib/brunel/brunel_ext/sumoselect/sumoselect.css -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/brunel_ext/sumoselect
    copying build/lib/brunel/brunel_util.py -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel
    copying build/lib/brunel/brunelWidgets.py -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel
    copying build/lib/brunel/D3_Template.html -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel
    copying build/lib/brunel/D3_Template.js -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel
    creating /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/lib
    copying build/lib/brunel/lib/brunel-core-0.8.jar -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/lib
    copying build/lib/brunel/lib/brunel-data-0.8.jar -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/lib
    copying build/lib/brunel/lib/gson-2.3.1.jar -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/lib
    copying build/lib/brunel/magics.py -> /Users/v2graeme/.local/lib/python3.5/site-packages/brunel
    byte-compiling /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/__init__.py to __init__.cpython-35.pyc
    byte-compiling /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/brunel.py to brunel.cpython-35.pyc
    byte-compiling /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/brunel_util.py to brunel_util.cpython-35.pyc
    byte-compiling /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/brunelWidgets.py to brunelWidgets.cpython-35.pyc
    byte-compiling /Users/v2graeme/.local/lib/python3.5/site-packages/brunel/magics.py to magics.cpython-35.pyc
    running install_egg_info
    Copying brunel.egg-info to /Users/v2graeme/.local/lib/python3.5/site-packages/brunel-0.8.0-py3.5.egg-info
    running install_scripts
    writing list of installed files to '/var/folders/sm/vn7jghs93x718m365s9n882m0000gn/T/pip-bxxle1di-record/install-record.txt'
    error: [Errno 2] No such file or directory: '/Users/v2graeme/.local/lib/python3.5/site-packages/jupyterpip/brunel/brunel_ext'
    Installing nbextension ...
    copying /Users/v2graeme/.local/lib/python3.5/site-packages/jupyterpip/brunel/brunel_ext -> /Users/v2graeme/Library/Jupyter/nbextensions/brunel_ext

**Comment by danrope** [comment]
Thanks!  Can you look to see if the following directory exists:

/Users/v2graeme/Library/Jupyter/nbextensions/brunel_ext

And, whether or not it contains several .js files?  If this directory does not exist or is empty, then a possible work-around might be to manually copy the contents from the folder below into :  /Users/v2graeme/Library/Jupyter/nbextensions/brunel_ext.   Then, restart the kernel, reload in the browser & try the samples again.

https://github.com/Brunel-Visualization/Brunel/tree/master/python/brunel/brunel_ext

**Comment by GraemeHutcheon** [comment]
That directory did not exist - I copied the files you suggested over and bingo I am now in business.
Thanks

**Comment by prempv** [comment]
Faced the same issue. Copying the files into suggested directory works.

**Comment by danrope** [comment]
Greetings.  I'd like to know whether this continues to be a problem in Brunel 1.1--or possibly--a more recent Jupyter version has fixed how the install works..

**Comment by danrope** [comment]
We believe this issue is resolved.  Please comment or re-open if it still occurs for you.
