### ISSUE TITLE
Package org.brunel.util.D3Integration.createBrunelJSON is not Callable

### ISSUE THREAD

**Issue by prempv** [Brunel-Visualization/Brunel#45]
I am running brunel within jupyter notebook. The notebook itself is installed as a part of the anaconda package and i used pip to install brunel. The installation had no warnings and went through smoothly. However when i try a simple chart it fails as below.

![image](https://cloud.githubusercontent.com/assets/5650874/11698056/d208081c-9e8a-11e5-8b22-f3813a2b1e14.png)

![image](https://cloud.githubusercontent.com/assets/5650874/11698095/116bf022-9e8b-11e5-8442-82031000f974.png)

**Comment by danrope** [comment]
Hello & thanks for letting us know.

Question:  What version of Java is installed (use "java -version") and can you also confirm the JAVA_HOME environment variable is set to the location of this Java installation?

Thanks.

**Comment by prempv** [comment]
I have open JDK 1.6 and yes JAVA_HOME is set.

**Comment by danrope** [comment]
OK.  Please try using JDK 1.7

**Comment by prempv** [comment]
It works with JDK 1.7. Thanks
