### ISSUE TITLE
Legends incorrectly positioned with mutliple graphs

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#48]
In the following Brunel, we would expect the legend to appear relative to the graph on the left.  Instead, it seems to be relative to the entire area for both graphs.

data('sample:whiskey.csv') x(Category) y(Price:linear) mean(Price) bar  color(Category)  | data('sample:whiskey.csv') x(ABV) y(Age)

**Comment by grahamwills** [comment]
Fixed in 0.9 development build
