### ISSUE TITLE
2nd graph has same default color ast the 1st

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#49]
Note:  This bug is happening on the 'develop' branch.  An element added via overlay "+" has the same default color as the first.  The following has point and bar, but the default color of the 2nd makes it invisible.

`data('sample:US States.csv') bar x(Region) yrange(Summer) iqr(Summer) + point x(Region) y(Summer) median(Summer) style('symbol:rect;height:2')`

Changing the style color to red makes this apparent:

`data('sample:US States.csv') bar x(Region) yrange(Summer) iqr(Summer) + point x(Region) y(Summer) median(Summer) style('symbol:rect;height:2;fill:red')`

**Comment by grahamwills** [comment]
Fixed in 0.9 development build
