### ISSUE TITLE
Missing Labels on Treemaps in Tiled charts

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#50]
When a Treemap is used as a tiled chart, the outer labels seem to have disappeared.  This is an issue observed only on the 0.9 branch.

`data('sample:whiskey.csv')  line x(age) y(rating) mean(rating) using(interpolate) label(country) split(country)                 bin(age:8)  color(#selection) legends(none) |        treemap x(category) interaction(select) size(#count) color(#selection) legends(none) sort(#count:ascending) bin(category:9)                tooltip(country) list(country)  label(#count) style('.labels .label {font-size:14px}')`

If the line chart is removed, the labels appear OK.

**Comment by grahamwills** [comment]
New label code transforms had not been applied to extra diagram labels. Fixed in 0.9
