### ISSUE TITLE
Mention that the js code from Deploy section requires the brunel.x.js library

### ISSUE THREAD

**Issue by figurebelow** [Brunel-Visualization/Brunel#52]
Hi,

I tried to copy/paste the js source generated from Deploy -> source code in ([Bubble chart of 2000 games](http://brunel.mybluemix.net/gallery_app/renderer?title=Bubble+chart+of+2000+games&brunel_src=data%28%27http%3A%2F%2Fwillsfamily.org%2Ffiles%2Fvis%2Fdata%2FBGG+Top+2000+Games.csv%27%29+bubble+color%28rating%29+size%28voters%29+sort%28rating%29+label%28title%29+tooltip%28title%2C+%23all%29+legends%28none%29+style%28%27*+{font-size%3A+7pt}%27%29&description=A+simple+bubble+chart+showing+the+top+ranked+games.+The+color+shows+the+BGG+rating+and+the+size+of+each+bubble+represents+the+number+of+voters+for+that+game.+The+data+is+already+sorted+by+rank%2C+so+no+sort+was+needed.+Data+is+from+March+2015)) 

However when I run the javascript code I get the following error:
`Undefined BrunelD3`
I investigated the example in JSFiddle and I saw it uses  http://brunelvis.org/js/brunel.0.7.min.js
so maybe it would help to mention that such library is required to get the exported code running fine.
(By the way I'm figuring out how to run this on Wordpress using my plugin, Wp-D3, importing that lib should be enough)

Thanks for the project, generating D3 code automatically is great!.

**Comment by danrope** [comment]
Thanks!  Agree this does need docs.  BTW, if you have trouble, try using http://brunelvis.org/js/brunel.0.8.min.js.  You also may need the following:
http://brunelvis.org/js/brunel.controls.0.8.min.js  (if the Brunel has interactive controls--like filter() ) plus jquery & jqueryui and there are also a few CSS files you may need as well.  

The Wordpress integration sounds very interesting!

**Comment by danrope** [comment]
A note has been added in the UI when deploying "Source Code".  We may want to enhance this at some point in the future to be smarter about which libraries are actually required and perhaps give the direct links right in the UI.
