### ISSUE TITLE
 warn("IPython.utils.traitlets has moved to a top-level traitlets package.")

### ISSUE THREAD

**Issue by gfilla** [Brunel-Visualization/Brunel#53]
Not sure if this is just my set up but I tried importing Brunel locally as well as in the docker container (https://hub.docker.com/r/brunelvis/notebook-minimal/) and I get this error message.

![image](https://cloud.githubusercontent.com/assets/6307720/12921621/c0cb71c4-cf13-11e5-9d2c-3b95fd61b8f6.png)

I am running ipykernel-4.2.2 and python 3.5 locally.  I was able to solve this error by adding the two import statements below.  Wanted to post this as a heads up for others that might see this.

import ipywidgets
import traitlets

**Comment by danrope** [comment]
Thanks!  We will address this ASAP.

**Comment by danrope** [comment]
Dependencies added, included in v1.0.1 on pypi.

**Comment by pari93411** [comment]
@gfilla sorry I tried it but it doesn't work for me
