### ISSUE TITLE
Extend filter(x)  to support value selection

### ISSUE THREAD

**Issue by dvasilen** [Brunel-Visualization/Brunel#57]
Consider: 
bar x(name) y(age) filter(country) 

As currently implemented Brunel renders all the values for the "country" in the chart by default and also selects all the values for the "country" in the filter dropdown. In some cases this default selection of all values does not make sense. As a possible enhancement we'd like to suggest extending the filter() to allow for a given selected value e.g. filter(country#US).

**Comment by danrope** [comment]
On develop branch, can now supply filter defaults which are reflected both in the initial visualization and the filter UI.  Examples:

All mpg >= 10
`filter(mpg:10)`

mpg between  from 10 to 30
`filter(mpg:10-30)`

Only South region
`filter(region:South)`

Only North & South region
`filter(region:["North", "South"])`

Will doc this in online tutorial as well.
