### ISSUE TITLE
Sum causing exception in some treemaps

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#6]
Use the "whiskey" data with the following Brunel:

` treemap x(Category, Brand) color(Rating) size(Price) sort(#count) label(ABV) tooltip(#all, Name) sum(Price) mean(Rating) min(ABV) list(Name:50)`

Getting exception:

`[err] java.lang.NullPointerException
[err] 	at org.brunel.data.summary.SummaryValues.get(SummaryValues.java:73)
[err] 	at org.brunel.data.modify.Summarize.make(Summarize.java:173)`

**Comment by grahamwills** [comment]
Issue was caused by a group containing nothing but null values;  added a fix to check for that
