### ISSUE TITLE
Compositions between maps and graphs with interactive selection do not render correctly initially

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#66]
Use the following Brunel on the attached data:

`map('usa') at(0,0,100,75) + x(Lat) y(Lon) size(Snowfall:200%) max(Snowfall) color(Source) label(Snowfall,City) tooltip(Snowfall, City, Source) interaction(filter)  at(0,0,100,75) + map(labels)  at(0,0,100,75) |  x(Time) bin(Time:20) color(#selection) opacity(#count) interaction(select) tooltip(Time)  at(0,85,100,100)`

There should be a graph at the bottom.  The graph can be made to appear by placing the mouse in the area where it is expected and "zooming" out.  Potentially related, note that panning gestures within this graph will cause the map to pan.

**Comment by danrope** [comment]
Attaching data..

[snowzilla.csv.txt](https://github.com/Brunel-Visualization/Brunel/files/138099/snowzilla.csv.txt)

**Comment by danrope** [comment]
I believe this has been fixed on /develop now.

**Comment by grahamwills** [comment]
and now on master
