### ISSUE TITLE
Ability to disable zoom / scroll / pan

### ISSUE THREAD

**Issue by eyce9000** [Brunel-Visualization/Brunel#69]
When using Brunel with Jupyter it would be nice to be able to disable zoom / scroll / pan. Every time I scroll through a notebook I have to be careful to keep my mouse a safe distance from the charts, otherwise I scroll them all to hell and have to re-render them to get them right again.

Maybe some sort of syntax to disable scrolling or a UI element to allow locking and unlocking scrolling?

**Comment by grahamwills** [comment]
The interaction 'none' can be used to disable panning and zooming: Add the following to any chart to turn it off:
                 `interaction(none)`

**Comment by eyce9000** [comment]
This does not seem to work for map charts. Has this been fixed? (I am down-level)

**Comment by danrope** [comment]
Confirmed.  We'll try to get this for 1.2
