### ISSUE TITLE
Axis label misplaced for composite graphs

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#7]
In the below the x-axis label appears at the bottom of the entire visualization instead of below the x-axis on the scatterplot.

Brunel syntax:

brunel bubble x(Division, Team) size(Win) color(Team) label(Team)  sum(Win) tooltip(#all) legends(none) interaction(select) at(0,-12,60,60) | x(Points_Allowed) y(Points_Scored) interaction(filter) tooltip(Year) at(60,10,100,45) | x(Year) y(Win) area stack split(Team) opacity(#selection)  style('stroke-width:.5') at(0,50,100,100) 

Data:  http://brunel.mybluemix.net/sample_data/BigTenWins.csv

**Comment by grahamwills** [comment]
Fixed
