### ISSUE TITLE
Bars do not start at zero

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#72]
This may be an edge case with this particular data since I rarely see this occur.  Use the attached data with:

`bar x(#row) y(a)`

The current result is the y-axis starts at 700.

**Comment by danrope** [comment]
[smalldata.csv.txt](https://github.com/Brunel-Visualization/Brunel/files/173936/smalldata.csv.txt)

**Comment by grahamwills** [comment]
Improved algorithm for decided whether to include zero. In development and ready to move to main for 1.2
