### ISSUE TITLE
Filtering does not work with percent

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#73]
User request:

> How do I create a chart that shows the percents of the total in each category? I tried the following, but it results in each bar showing 100%. In this case, a bar chart of counts would have the right shape, but the idea was that I wanted to add a filter to show how the distribution of percentages in JobSatisfaction changes by JobLevel

`bar x(JobSatisfaction) y(#count) percent(#count)`

**Comment by grahamwills** [comment]
We added an option to the percent summary to allow a percent to be takes as part of the overall data, rather than as part of the data for each X category. The syntax is as follows:

data('sample:US States.csv') bar x(region) y(#count) percent(#count:overall)
