### ISSUE TITLE
Issues with CO2 Scala example notebook

### ISSUE THREAD

**Issue by svenhafeneger** [Brunel-Visualization/Brunel#74]
I tested the CO2 Scala notebook with IBM Analytics for Apache Spark (Scala 2.10, Spark 1.6.0).

The first map shows quite a lot of details, so that the interactive usage is a little bit limited through slow responses.

For the second map, the code is not creating an output cell and no map is visualized.

**Comment by danrope** [comment]
Hello,
We have posted a test version of Brunel 1.2 here:  http://www.brunelvis.org/jar/spark-kernel-brunel-all-1.2.jar 

You can now use `map(low)` which will use a lower resolution map which should pan/zoom better.  Also, let us know if the 2nd graph still does not appear.

**Comment by svenhafeneger** [comment]
I have tested the sample notebook with http://www.brunelvis.org/jar/spark-kernel-brunel-all-1.2.jar.
The issues are gone with the first map are gone and the second map is visible.
Thanks.
