### ISSUE TITLE
Include Geo data in distribution

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#76]
BuilderOptions provides the location of the required Brunel Geo files; however, currently there is no convenient way to get the geo data.  Suggest including a .zip file containing the required Geo data within the release distribution.  Or, minimally, added to github.

**Comment by danrope** [comment]
Re-assign to me once Geo files in Git.

**Comment by grahamwills** [comment]
Added in core/etc as a zip file -- feel free to move to a better locations (maybe one of the web server locations?)

**Comment by danrope** [comment]
Added to the distribution .zip & tar
