### ISSUE TITLE
Full control over required JS library locations

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#77]
BuilderOptions currently provides a setting for the location of JS libraries needed by Brunel.  Improvements needed are:
* Brunel in Toree notebooks need to use BuilderOptions settings instead of hard-coding locations
* Allow the user control over where D3, JQuery or any other required JS libraries are located

**Comment by danrope** [comment]
For now, we will add a single environment variable:  BRUNEL_CONFIG.  Eventually this can move to a file.

Within this variable, variable we can set:
jvm:  The path to the JVM used by Jpype (Python notebooks only)
locd3:  The URL to find D3 (Python/Toree notebooks)
locJavaScript:  The location to the Brunel JS files (Python/Toree notebooks)

**Comment by danrope** [comment]
Added on 1.1.  Only added support for D3, brunel JS/CSS & brunel geo data loading since control over JQuery is not needed for notebook deployments which was the main issue this was intended to address.

**Comment by rbrasier** [comment]
If using a Jupyter notebook via python, how can I set locMaps environment variable to specify a different source for the geo json files given that this variable does not appear in brunel_util.py (Brunel/python/brunel/brunel_util.py)?

I've can successfully set the the d3 to point to a different location, however I can't get locMaps to be updated via the same environment variable.  How can this be achieved?

**Comment by danrope** [comment]
How are you setting the env variable?

Indeed, some settings in the environment variable are read and used during Java execution. So, it is likely this environment variable must be set directly in the OS prior to starting Jupyter.

**Comment by rbrasier** [comment]
I'm setting the environment variable via export i.e.:

~ $ export BRUNEL_CONFIG="locMaps=
http://localhost/brunel_geo;locd3=http://localhost2/d3.js"
 and then
~ $ jupyter notebook

When I create a new notebook, the locd3 is pointing to the correct location
(localhost). however the locMaps location is still pointing to brunelvis.org

Could this be the scope of the environment variable where java can't see
this variable but python can? (are they run in the same context?)

(Screenshots attached)

**Comment by danrope** [comment]
OK.  This is indeed a defect.  Re-opening..

**Comment by danrope** [comment]
Fixed on develop.  Confirmed loaded file locations in python & R notebooks from the following env variable.  Note that requirejs is used to load D3, so the trailing ".js" is omitted.  Also note that the actual path to the map content is `/notebooks/data/geo/2.0/high/..`  (`high, low, or med`).  Brunel will pre-pend the version number to the supplied path in the env. var.

`BRUNEL_CONFIG=locMaps= http://localhost:8888/tree/notebooks/data/geo;locd3=http://localhost:8888/files/notebooks/data/d3/d3`

**Comment by rbrasier** [comment]
Thanks :)
