### ISSUE TITLE
More of a usability question.  I am displaying to bubble data side by side with | and want green color for left and red for right.  How to do that?

### ISSUE THREAD

**Issue by skuchak** [Brunel-Visualization/Brunel#78]

**Comment by danrope** [comment]
You can use styles to do this:

`data('sample:US States.csv') bubble label(abbr) size(population) style("fill:green") | bubble size(income) style("fill:red")`

For docs, see the "Guides & Style" section in the tutorial:  http://brunel.mybluemix.net/docs/
