### ISSUE TITLE
Graph misplaced when tile and overlay are combined

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#8]
In the below, the scatterplot appears in the bottom left when an overlay is used instead of in the upper right where it is expected.  Also, it is not clear how to use "at" when we have overlays and tile combined.

Brunel: (use  height=700, width=900)

bubble x(Division, Team) size(Win) color(Team) label(Team)  sum(Win) tooltip(#all) legends(none) interaction(select) at(0,-12,60,60) | x(Points_Allowed) y(Points_Scored) interaction(filter) tooltip(Year) at(60,10,100,45) + x(Points_Allowed) y(Points_Scored) fit(Points_Scored) line  at(60,10,100,45) | x(Year) y(Win) area stack split(Team) opacity(#selection)  style('stroke-width:.5') at(0,50,100,100) 

Data: http://brunel.mybluemix.net/sample_data/BigTenWins.csv

**Comment by grahamwills** [comment]
fixed -- only one "at" is needed in a n overlaid chart. If multiple are defined, only the first is used
