### ISSUE TITLE
Trying to show below data in a bubble. Name is getting truncated in the bubble when sorted by estimate_rows or size_in_mb.   I want to display a seq # in the bubble and use legend to display seq# and Name.  How to do this sort of legend? 

### ISSUE THREAD

**Issue by skuchak** [Brunel-Visualization/Brunel#81]
Seq	NAME	ESTIMATE_ROWS	SIZE_IN_MB
1	PS_VCHR_ACCTG_LINE	13660402	8407
2	PS_DEPR_RPT	26562814	7051
3	PS_JRNL_LN	14919098	3789
4	PS_GT_IHUB_ENT1_ST	5405441	2357
5	PSAPMSGPUBDATA	1488500	2049
6	PS_DISTRIB_LINE	2427246	1793
7	PS_GT_IHUB_SRC1	5357302	1475
8	PS_GT_VCHR_STG	656110	1472
9	PS_EOAW_WL	6756589	1408
10	PS_VOUCHER	1685282	1345
11	PS_VOUCHER_LINE	2208554	1281

**Comment by grahamwills** [comment]
In Brunel we have pretty minimal legends -- for more complex legends we recommend the use of two charts, making one of them a legend. So for your data, you might have the following as your base (bubble) chart:

`bubble color(SIZE_IN_MB) size(ESTIMATE_ROWS) label(Seq) legends(none) sort(ESTIMATE_ROWS) tooltip(name)`

the we can make a 'legend' using the following:

'point axes(none) label('#',seq, ' ', name) stack color(SIZE_IN_MB)'

and we stick the two together using the '|' operator to put things side by side (and give them custom positions using the `at` command to give the full result:

`bubble color(SIZE_IN_MB) size(ESTIMATE_ROWS) label(Seq) legends(none) sort(ESTIMATE_ROWS) at(0,0,50,100) | point axes(none) label('#',seq, ' ', name) stack color(SIZE_IN_MB) at (25,0,100,100)`

**Comment by skuchak** [comment]
Thanks a tonne.  I was able to display the legend. I need to be able to 
sort the legend by Seq.  Is that possible in the label?  Also is it 
possible to place a title(text) below the bubles and above the legend?
 label('#',seq, ' ', name)


thanks,
Sampurna Kuchakulla
IT Generalist | Cloud Managed Application Services
IBM Cloud
Contact: (317) 418-0706
skuchak@us.ibm.com
