### ISSUE TITLE
Filter causes visible data split when statistic used

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#9]
See:  http://brunel.mybluemix.net/gallery_app/renderer?title=Filtered+Bar+Chart&brunel_src=data%28%27http%3A%2F%2Fbrunel.mybluemix.net%2Fsample_data%2Fwhiskey.csv%27%29+x%28Category%29+y%28Price%3Alinear%29+mean%28Price%29+bar+filter%28Age%2C+ABV%29&description=Average+whiskey+price+per+category+filtered+by+age+and+alcohol+content&width=600&height=600&control_height=100

When filtering, the bars seem to be split even though a summarization statistic has been applied.

**Comment by grahamwills** [comment]
Ensured that filters are not considered as groups when summarizing
