### ISSUE TITLE
Interactive hover drop lines with labels

### ISSUE THREAD

**Issue by lkittock** [Brunel-Visualization/Brunel#90]
I often want charts with interactive reference lines, which drop to the X and Y axes when you hover, and give you the actual value for that point/line/etc.

For example, look at the stock chart here:

https://finance.yahoo.com/echarts?s=IBM+Interactive#{"showSma":true,"smaColors":"#cc0000","smaPeriods":"100","smaWidths":"1","smaGhosting":"0","range":"3mo","allowChartStacking":true}

**Comment by dpierucci** [comment]
If possible, please also add the interactive drop lines when you hover on either of the axes as well. Thanks!

**Comment by danrope** [comment]
This should be done as an option on tooltip().  Perhaps "crosshairs".  We may want assistance in the implementation.
