### ISSUE TITLE
Some styles no longer workng 

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#92]
On develop, try: 

`bar x(region) y(#count) title('Count Per Region', 'US Regions':footer) style('.header {fill:orange}')`

The color of the header remains blue.  Other label style properties are also not functioning.  Also:

`x(region) y(#count) style('fill:red')`

--> Points are not red.

**Comment by grahamwills** [comment]
Fixed in develop -- had a null value being written out causing illegal style code.
