### ISSUE TITLE
Binning does not work with maps

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#93]
Use this Brunel:

`data('sample:US States.csv') map x(State) color(Income:blues) + map(labels) + data('sample:airports2008na.csv') x(Long) y(Lat) size(Flights:500%) bin(Long, Lat) legends(none)`

The long/lat values should be binned & plotted, but instead a single point appears at top/left.

**Comment by grahamwills** [comment]
Fixed on develop -- looks nice using following command:

data('sample:US States.csv') map(low) x(State) color(Income:blues) + data('sample:airports2008na.csv') x(Long) y(Lat) color(#count:reds) size(Flights:500%) tooltip(iata) bin(Long:40, Lat:40) sum(flights) list(iata) legends(none)
