### ISSUE TITLE
Enhancement Request:  Animation Controller

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#95]
Add a new interactive feature that allows animation over a field for a given graph (often it is 'time').  Include a UI that will show play/stop controls and a slider to manually scroll through the animated frames.

**Comment by dpierucci** [comment]
Nice feature guys! 

Graham, 
I believe that you said the following composition should show the animation, but it does not.

data('sample:US States.csv') x(winter) y(summer) + line x(winter) y(70) effect(enter)

Is that syntax specified correctly?

Thanks!

**Comment by danrope** [comment]
I think this is a comment intended for issue  https://github.com/Brunel-Visualization/Brunel/issues/94

**Comment by dpierucci** [comment]
Oops, yes. Sorry about that. I will add it to #94.

**Comment by danrope** [comment]
Added feature, docs & made required notebook changes.  Basic syntax:

`data('cars') bar x(origin) y(mpg) mean(mpg) animate(year)`
