### ISSUE TITLE
Enhancement Request: Add a way to get the data for a user's selections

### ISSUE THREAD

**Issue by dpierucci** [Brunel-Visualization/Brunel#96]
Add a feature to get the data associated with a user's selections. For example, if a bar chart is showing a bar for males and a bar for females, and the user selects the bar for females, we need a way to get that information.

**Comment by grahamwills** [comment]
Adding a feature into 1.2, but not documenting it as it is "experimental" and might change later on review:

Expanding the brunel command `Interaction` by allowing the option `call` to be specified, usually with two extra parameters which define the event to hook up to and the function to call, like so, for a bar chart:

`bar x(Region) y(#count) sort(#count) tooltip(#all) interaction(call:click:func)`

This will call the function _func_ when the element is clicked on. The function si called with the following parameters:

 * row -- the row in the processed data (after aggregation, series, summaries, etc.)
 * value -- the value of the key fields for the item hit. May be an array (for multiple keys) or a comma-separated list of values if the key is #row
 * data -- the processed data object
 * element -- description of the element; in particular element.fields.key gives the key fields for this element

When the function is called "this" is assigned to the SVG element that was interacted with



If no function is specified, a debugging function is sued which simply puts up an alert with basic data, and writes full data to the console.

**Comment by grahamwills** [comment]
This is not fixed in stone, and (in particular) we may change the parameters being passed down, but it should be ready to trial.
